
CREATE TABLE admin(
	adminname varchar(50) NOT NULL,
	password varchar(50) NOT NULL
)

insert into admin(adminname,password) values('admin','admin');

CREATE TABLE system_info(
	companyName varchar(50) NULL,
	copyright varchar(500) NULL,
	version varchar(10) NULL,
	website varchar(50) NULL
);

drop table if exists username;

CREATE TABLE username(
	nameid int NOT NULL auto_increment,
	name varchar(50) NOT NULL,
	sex varchar(50) NULL,
	password varchar(50) NULL,
	name_en nvarchar(50) NULL,
	workj varchar(90) NULL,
	email varchar(90) NULL,
	worktel varchar(50) NULL,
	userdate varchar(50) NULL,
	yjxs varchar(50) NULL,
	hometel nvarchar(50) NULL,
	user_ip varchar(50) NULL,
	ipbd char(10) NULL,
	err int NULL,
	mail_user nvarchar(50) NULL,
	mail_password nvarchar(50) NULL,
	mail_smtp nvarchar(90) NULL,
	restrain_id int NULL,
	department_id int NULL,
	department_name int NULL
);

insert into username(name,password,restrain_id,department_id) values('oa_admin','123$%^',1,1)

CREATE TABLE restrain(
	id int NOT NULL auto_increment,
	restrain_name char(65) NOT NULL,
	qzadd char(10) NULL,
	qzmod char(10) NULL,
	qzdel char(10) NULL,
	qzview char(10) NULL,
	qzview_yes char(10) NULL,
	qzzt char(10) NULL,
	xhadd char(10) NULL,
	xhmod char(10) NULL,
	xhdel char(10) NULL,
	xhview char(10) NULL,
	xhview_yes char(10) NULL,
	xhzt char(10) NULL,
	linkadd char(10) NULL,
	linkmod char(10) NULL,
	linkdel char(10) NULL,
	linkview char(10) NULL,
	linkview_yes char(10) NULL,
	linkzt char(10) NULL,
	hzadd char(10) NULL,
	hzmod char(10) NULL,
	hzdel char(10) NULL,
	hzview char(10) NULL,
	hzview_yes char(10) NULL,
	hzzt char(10) NULL,
	supadd char(10) NULL,
	supmod char(10) NULL,
	supdel char(10) NULL,
	supview char(10) NULL,
	supview_yes char(10) NULL,
	supzt char(10) NULL,
	actadd char(10) NULL,
	actmod char(10) NULL,
	actdel char(10) NULL,
	actview char(10) NULL,
	actview_yes char(10) NULL,
	actzt char(10) NULL,
	opadd char(10) NULL,
	opmod char(10) NULL,
	opdel char(10) NULL,
	opview char(10) NULL,
	opview_yes char(10) NULL,
	opzt char(10) NULL,
	quoteadd char(10) NULL,
	quotemod char(10) NULL,
	quotedel char(10) NULL,
	quoteview char(10) NULL,
	quoteview_yes char(10) NULL,
	quotezt char(10) NULL,
	profl nvarchar(100) NULL,
	proadd char(10) NULL,
	promod char(10) NULL,
	prodel char(10) NULL,
	proview char(10) NULL,
	proview_yes char(10) NULL,
	prozt char(10) NULL,
	r_sup_xj_add char(10) NULL,
	r_sup_xj_mod char(10) NULL,
	r_sup_xj_del char(10) NULL,
	r_sup_xj_view char(10) NULL,
	r_sup_xj_zt char(10) NULL,
	cgadd char(10) NULL,
	cgmod char(10) NULL,
	cgdel char(10) NULL,
	cgview char(10) NULL,
	cgview_yes char(10) NULL,
	cgzt char(10) NULL,
	tradd char(10) NULL,
	trmod char(10) NULL,
	trdel char(10) NULL,
	trview char(10) NULL,
	trview_yes char(10) NULL,
	trzt char(10) NULL,
	hdadd char(10) NULL,
	hdmod char(10) NULL,
	hddel char(10) NULL,
	hdview char(10) NULL,
	hdview_yes char(10) NULL,
	hdzt char(10) NULL,
	r_yfgladd char(10) NULL,
	r_yfglmod char(10) NULL,
	r_yfgldel char(10) NULL,
	r_yfglview char(10) NULL,
	r_yfglview_yes char(10) NULL,
	r_yfglzt char(10) NULL,
	workadd char(10) NULL,
	workmod char(10) NULL,
	workdel char(10) NULL,
	workview char(10) NULL,
	workview_yes char(10) NULL,
	workzt char(10) NULL,
	r_month_jh_add char(10) NULL,
	r_month_jh_mod char(10) NULL,
	r_month_jh_del char(10) NULL,
	r_month_jh_view char(10) NULL,
	r_month_jh_view_yes char(10) NULL,
	r_month_jh_zt char(10) NULL,
	r_date_r_add char(10) NULL,
	r_date_r_mod char(10) NULL,
	r_date_r_del char(10) NULL,
	r_date_r_view char(10) NULL,
	r_date_r_view_yes char(10) NULL,
	r_date_r_zt char(10) NULL,
	r_week_r_add char(10) NULL,
	r_week_r_mod char(10) NULL,
	r_week_r_del char(10) NULL,
	r_week_r_view char(10) NULL,
	r_week_r_view_yes char(10) NULL,
	r_week_r_zt char(10) NULL,
	r_month_r_add char(10) NULL,
	r_month_r_mod char(10) NULL,
	r_month_r_del char(10) NULL,
	r_month_r_view char(10) NULL,
	r_month_r_view_yes char(10) NULL,
	r_month_r_zt char(10) NULL,
	xmadd char(10) NULL,
	xmmod char(10) NULL,
	xmdel char(10) NULL,
	xmview char(10) NULL,
	xmview_yes char(10) NULL,
	xmzt char(10) NULL,
	r_cus_xj_add char(10) NULL,
	r_cus_xj_mod char(10) NULL,
	r_cus_xj_del char(10) NULL,
	r_cus_xj_view char(10) NULL,
	r_cus_xj_zt char(10) NULL,
	r_htgl_add char(10) NULL,
	r_htgl_mod char(10) NULL,
	r_htgl_del char(10) NULL,
	r_htgl_view char(10) NULL,
	r_htgl_view_yes char(10) NULL,
	r_htgl_zt char(10) NULL,
	r_sam_add char(10) NULL,
	r_sam_mod char(10) NULL,
	r_sam_del char(10) NULL,
	r_sam_view char(10) NULL,
	r_sam_zt char(10) NULL,
	subadd char(10) NULL,
	submod char(10) NULL,
	subdel char(10) NULL,
	subview char(10) NULL,
	subview_yes char(10) NULL,
	subzt char(10) NULL,
	manadd char(10) NULL,
	manmod char(10) NULL,
	mandel char(10) NULL,
	manview char(10) NULL,
	manview_yes char(10) NULL,
	manzt char(10) NULL,
	rwadd char(10) NULL,
	rwmod char(10) NULL,
	rwdel char(10) NULL,
	rwview char(10) NULL,
	rwview_yes char(10) NULL,
	rwzt char(10) NULL,
	fyadd char(10) NULL,
	fymod char(10) NULL,
	fydel char(10) NULL,
	fyview char(10) NULL,
	fyview_yes char(10) NULL,
	fyzt char(10) NULL,
	r_jkgl_add char(10) NULL,
	r_jkgl_mod char(10) NULL,
	r_jkgl_del char(10) NULL,
	r_jkgl_view char(10) NULL,
	r_jkgl_view_yes char(10) NULL,
	r_jkgl_zt char(10) NULL,
	r_fksq_add char(10) NULL,
	r_fksq_mod char(10) NULL,
	r_fksq_del char(10) NULL,
	r_fksq_view char(10) NULL,
	r_fksq_view_yes char(10) NULL,
	r_fksq_zt char(10) NULL,
	r_zzsq_add char(10) NULL,
	r_zzsq_mod char(10) NULL,
	r_zzsq_del char(10) NULL,
	r_zzsq_view char(10) NULL,
	r_zzsq_zt char(10) NULL,
	r_jcsq_add char(10) NULL,
	r_jcsq_mod char(10) NULL,
	r_jcsq_del char(10) NULL,
	r_jcsq_view char(10) NULL,
	r_jcsq_zt char(10) NULL,
	r_xzyd_add char(10) NULL,
	r_xzyd_mod char(10) NULL,
	r_xzyd_del char(10) NULL,
	r_xzyd_view char(10) NULL,
	r_xzyd_zt char(10) NULL,
	r_ccsq_add char(10) NULL,
	r_ccsq_mod char(10) NULL,
	r_ccsq_del char(10) NULL,
	r_ccsq_view char(10) NULL,
	r_ccsq_zt char(10) NULL,
	r_bgyp_add char(10) NULL,
	r_bgyp_mod char(10) NULL,
	r_bgyp_del char(10) NULL,
	r_bgyp_view char(10) NULL,
	r_bgyp_zt char(10) NULL,
	r_nbqc_add char(10) NULL,
	r_nbqc_mod char(10) NULL,
	r_nbqc_del char(10) NULL,
	r_nbqc_view char(10) NULL,
	r_nbqc_zt char(10) NULL,
	r_yjsq_add char(10) NULL,
	r_yjsq_mod char(10) NULL,
	r_yjsq_del char(10) NULL,
	r_yjsq_view char(10) NULL,
	r_yjsq_zt char(10) NULL,
	r_spbm_add char(10) NULL,
	r_spbm_mod char(10) NULL,
	r_spbm_del char(10) NULL,
	r_spbm_view char(10) NULL,
	r_spbm_zt char(10) NULL,
	thadd char(10) NULL,
	thmod char(10) NULL,
	thdel char(10) NULL,
	thview char(10) NULL,
	thview_yes char(10) NULL,
	thzt char(10) NULL,
	r_xphh_add char(10) NULL,
	r_xphh_mod char(10) NULL,
	r_xphh_del char(10) NULL,
	r_xphh_view char(10) NULL,
	r_xphh_zt char(10) NULL,
	serveradd char(10) NULL,
	servermod char(10) NULL,
	serverdel char(10) NULL,
	serverview char(10) NULL,
	serverview_yes char(10) NULL,
	serverzt char(10) NULL,
	tsadd char(10) NULL,
	tsmod char(10) NULL,
	tsdel char(10) NULL,
	tsview char(10) NULL,
	tsview_yes char(10) NULL,
	tszt char(10) NULL,
	wxadd char(10) NULL,
	wxmod char(10) NULL,
	wxdel char(10) NULL,
	wxview char(10) NULL,
	wxview_yes char(10) NULL,
	wxzt char(10) NULL,
	r_hyzc_add char(10) NULL,
	r_hyzc_mod char(10) NULL,
	r_hyzc_del char(10) NULL,
	r_hyzc_view char(10) NULL,
	r_hyzc_view_yes char(10) NULL,
	r_hyzc_zt char(10) NULL,
	r_mtxc_add char(10) NULL,
	r_mtxc_mod char(10) NULL,
	r_mtxc_del char(10) NULL,
	r_mtxc_view char(10) NULL,
	r_mtxc_view_yes char(10) NULL,
	r_mtxc_zt char(10) NULL,
	mactadd char(10) NULL,
	mactmod char(10) NULL,
	mactdel char(10) NULL,
	mactview char(10) NULL,
	mactview_yes char(10) NULL,
	mactzt char(10) NULL,
	jzdsadd char(10) NULL,
	jzdsmod char(10) NULL,
	jzdsdel char(10) NULL,
	jzdsview char(10) NULL,
	jzdsview_yes char(10) NULL,
	jzdszt char(10) NULL,
	zskadd char(10) NULL,
	zskmod char(10) NULL,
	zskdel char(10) NULL,
	zskview char(10) NULL,
	zskview_yes char(10) NULL,
	zskzt char(10) NULL,
	flfgadd char(10) NULL,
	flfgmod char(10) NULL,
	flfgdel char(10) NULL,
	flfgview char(10) NULL,
	flfgview_yes char(10) NULL,
	flfgzt char(10) NULL,
	r_wlz_add char(10) NULL,
	r_wlz_mod char(10) NULL,
	r_wlz_del char(10) NULL,
	r_wlz_view char(10) NULL,
	r_wlz_view_yes char(10) NULL,
	r_wlz_zt char(10) NULL,
	zjadd char(10) NULL,
	zjmod char(10) NULL,
	zjdel char(10) NULL,
	zjview char(10) NULL,
	zjview_yes char(10) NULL,
	zjzt char(10) NULL,
	r_wage_add char(10) NULL,
	r_wage_mod char(10) NULL,
	r_wage_del char(10) NULL,
	r_wage_view char(10) NULL,
	r_wage_zt char(10) NULL,
	fkhzadd char(10) NULL,
	fkhzmod char(10) NULL,
	fkhzdel char(10) NULL,
	fkhzview char(10) NULL,
	fkhzview_yes char(10) NULL,
	fkhzzt char(10) NULL,
	skhzadd char(10) NULL,
	skhzmod char(10) NULL,
	skhzdel char(10) NULL,
	skhzview char(10) NULL,
	skhzview_yes char(10) NULL,
	skhzzt char(10) NULL,
	fkmod char(10) NULL,
	fkdel char(10) NULL,
	fkview char(10) NULL,
	fkview_yes char(10) NULL,
	fkzt char(10) NULL,
	r_wx_gt_view char(10) NULL,
	r_wx_gt_zt char(10) NULL,
	skmod char(10) NULL,
	skdel char(10) NULL,
	skview char(10) NULL,
	skview_yes char(10) NULL,
	skzt char(10) NULL,
	qkmod char(10) NULL,
	qkdel char(10) NULL,
	qkview char(10) NULL,
	qkview_yes char(10) NULL,
	qkzt char(10) NULL,
	r_thje_mod char(10) NULL,
	r_thje_del char(10) NULL,
	r_thje_view char(10) NULL,
	r_thje_view_yes char(10) NULL,
	r_thje_zt char(10) NULL,
	intadd char(10) NULL,
	intmod char(10) NULL,
	intdel char(10) NULL,
	intview char(10) NULL,
	intview_yes char(10) NULL,
	intzt char(10) NULL,
	outadd char(10) NULL,
	outmod char(10) NULL,
	outdel char(10) NULL,
	outview char(10) NULL,
	outview_yes char(10) NULL,
	outzt char(10) NULL,
	r_dzzx_zt char(10) NULL,
	r_xscp_zt char(10) NULL,
	syszt char(10) NULL,
	jcfxzt char(10) NULL,
	custzyzt char(10) NULL,
	cgxjxx nchar(10) NULL
);

CREATE TABLE department(
	id int IDENTITY(1,1) NOT NULL,
	departname nvarchar(80) NOT NULL,
	dept_types int NULL,
	dept_code nvarchar(50) NOT NULL,
	remark ntext NULL,
	leader varchar(50) NULL
);




CREATE TABLE restrain_gp(
	id int IDENTITY(1,1) NOT NULL,
	restrain_name nvarchar(50) NULL,
	pro_ck nvarchar(50) NULL,
	pro_zt char(10) NULL,
	pro_add char(10) NULL,
	pro_mod char(10) NULL,
	pro_del char(10) NULL,
	pro_view char(10) NULL,
	proview_price char(10) NULL
);

insert into username(name,password) values('admin','admin');

CREATE TABLE quote(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	quotedatetime varchar(50) NULL,
	in_number nvarchar(50) NULL,
	co_number char(30) NULL,
	coname varchar(150) NULL,
	cotel varchar(50) NULL,
	coaddr varchar(150) NULL,
	cofax varchar(50) NULL,
	linkman varchar(50) NULL,
	linktel varchar(50) NULL,
	linkwap varchar(50) NULL,
	linkemail varchar(50) NULL,
	airport varchar(260) NULL,
	tr_types nvarchar(90) NULL,
	q_tr_date nvarchar(90) NULL,
	payment nvarchar(100) NULL,
	bz nvarchar(150) NULL,
	content ntext NULL,
	man varchar(50) NULL,
	spman nvarchar(50) NULL,
	states char(10) NULL,
	spyj nvarchar(200) NULL,
	hb char(10) NULL,
	fveight decimal(18, 2) NULL,
	insurance decimal(18, 2) NULL,
	commission decimal(18, 2) NULL,
	discount decimal(18, 2) NULL,
	in_no int NULL,
	dept nvarchar(50) NULL,
	deptjb char(15) NULL,
	acct nvarchar(50) NULL
)

CREATE TABLE ht(
	id int IDENTITY(1,1) NOT NULL,
	ht_topic nvarchar(200) NULL,
	ht_mycom nvarchar(100) NOT NULL,
	ht_addr nvarchar(100) NULL,
	ht_customer nvarchar(90) NOT NULL,
	ht_number nvarchar(30) NOT NULL,
	ht_datetime datetime NOT NULL,
	ht_tk ntext NULL,
	ht_mycom_addr nvarchar(100) NULL,
	ht_cust_addr nvarchar(100) NULL,
	ht_mycom_man char(50) NULL,
	ht_cust_man char(50) NULL,
	ht_mycom_tel nvarchar(50) NULL,
	ht_cust_tel nvarchar(50) NULL,
	ht_mycom_bank nvarchar(50) NULL,
	ht_cust_bank nvarchar(50) NULL,
	ht_mycom_banknumber nvarchar(30) NULL,
	ht_cust_banknumber nvarchar(50) NULL,
	ht_mycom_post char(50) NULL,
	ht_cust_post char(50) NULL,
	ht_mycom_nsnumber nvarchar(50) NULL,
	ht_cust_nsnumber nvarchar(50) NULL,
	states char(15) NULL,
	username char(15) NULL,
	dept nvarchar(50) NULL,
	deptjb char(30) NULL,
	spman char(15) NULL,
	spyj nvarchar(350) NULL,
	fspman char(30) NULL,
	fspyj nvarchar(450) NULL,
	co_number char(15) NULL,
	in_no int NULL
);

CREATE TABLE sample(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	man varchar(30) NOT NULL,
	sub nvarchar(60) NULL,
	coname varchar(60) NOT NULL,
	yj varchar(50) NOT NULL,
	money char(10) NOT NULL,
	habitus varchar(10) NOT NULL,
	datetime datetime NOT NULL,
	senddate nvarchar(100) NULL,
	delivery_terms nvarchar(200) NULL,
	delivery_date nvarchar(200) NULL,
	airport nvarchar(200) NULL,
	tbyq nvarchar(200) NULL,
	remarks ntext NULL,
	state varchar(50) NOT NULL,
	spman varchar(50) NULL,
	spdate nvarchar(50) NULL,
	spyj nvarchar(300) NULL,
	fif char(10) NULL,
	cwman char(15) NULL,
	cwdate nvarchar(50) NULL,
	cwyj varchar(300) NULL,
	dept char(30) NULL,
	deptjb char(10) NULL,
	linkman nvarchar(50) NULL,
	fveight decimal(18, 2) NULL,
	insurance decimal(18, 2) NULL,
	in_no int NULL,
	syyj nvarchar(200) NULL
);

CREATE TABLE sam_pro(
	id int IDENTITY(1,1) NOT NULL,
	ddid varchar(50) NOT NULL,
	epro varchar(150) NOT NULL,
	num int NOT NULL,
	fypronum int NULL,
	unit varchar(50) NULL,
	cpro varchar(150) NULL,
	cpro2 nvarchar(50) NULL,
	rale_types varchar(50) NULL,
	rale decimal(10, 2) NULL,
	supplier varchar(150) NULL,
	pricehb nvarchar(30) NOT NULL,
	salejg decimal(18, 2) NOT NULL,
	selljg decimal(18, 2) NULL,
	money varchar(50) NULL,
	fyproall char(15) NULL,
	wid char(10) NULL,
	pro_r_date nvarchar(50) NULL,
	pro_sr_date nvarchar(50) NULL,
	remark nvarchar(350) NULL,
	pro_snum int NULL,
	pro_sc_num int NULL,
	xj_date nvarchar(50) NULL
)

CREATE TABLE subscribe(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	man varchar(30) NOT NULL,
	subck nvarchar(50) NULL,
	sub nvarchar(100) NULL,
	coname varchar(100) NOT NULL,
	yj decimal(18, 0) NOT NULL,
	money char(10) NOT NULL,
	item varchar(150) NULL,
	mode varchar(150) NULL,
	source int NOT NULL,
	trade varchar(50) NULL,
	habitus varchar(10) NOT NULL,
	datetime datetime NOT NULL,
	senddate nvarchar(100) NULL,
	tbyq ntext NULL,
	remarks ntext NULL,
	state varchar(10) NOT NULL,
	spman varchar(50) NULL,
	spdate nvarchar(50) NULL,
	spyj nvarchar(300) NULL,
	fif char(10) NULL,
	cwman char(15) NULL,
	cwdate nvarchar(50) NULL,
	cwyj varchar(300) NULL,
	dept char(60) NULL,
	deptjb char(30) NULL,
	tr nvarchar(50) NULL,
	tr_addr nvarchar(300) NULL,
	tr_man nvarchar(50) NULL,
	tr_tel nvarchar(80) NULL,
	yf_types nvarchar(50) NULL,
	yf_money decimal(18, 2) NULL,
	fy_number char(20) NULL,
	ware_remark nvarchar(300) NULL,
	in_no int NULL,
	p_states nvarchar(50) NULL,
	sub_time char(30) NULL,
	s_check char(10) NULL,
	ware_man char(30) NULL,
	cg_man char(15) NULL,
	send_date char(15) NULL,
	other_fy decimal(18, 2) NULL,
	custno varchar(50) NULL,
	del_remark ntext NULL,
	return_remark ntext NULL
)

CREATE TABLE workreport_r(
	id int IDENTITY(1,1) NOT NULL,
	w_menber nvarchar(25) NOT NULL,
	w_datetime datetime NULL,
	w_man nvarchar(15) NULL,
	w_dept varchar(50) NULL,
	w_deptjb char(10) NULL,
	w_coname nvarchar(90) NULL,
	w_xmid char(10) NULL,
	w_programer nvarchar(90) NULL,
	w_remark nvarchar(100) NULL,
	w_coname1 nvarchar(90) NULL,
	w_xmid1 char(10) NULL,
	w_programer1 nvarchar(90) NULL,
	w_remark1 nvarchar(100) NULL,
	w_coname2 nvarchar(90) NULL,
	w_xmid2 char(10) NULL,
	w_programer2 nvarchar(90) NULL,
	w_remark2 nvarchar(100) NULL,
	w_coname3 nvarchar(90) NULL,
	w_xmid3 char(10) NULL,
	w_programer3 nvarchar(90) NULL,
	w_remark3 nvarchar(100) NULL,
	w_coname4 nvarchar(90) NULL,
	w_xmid4 char(10) NULL,
	w_programer4 nvarchar(90) NULL,
	w_remark4 nvarchar(100) NULL,
	w_coname5 nvarchar(90) NULL,
	w_xmid5 char(10) NULL,
	w_programer5 nvarchar(90) NULL,
	w_remark5 nvarchar(100) NULL,
	w_coname6 nvarchar(90) NULL,
	w_xmid6 char(10) NULL,
	w_programer6 nvarchar(90) NULL,
	w_remark6 nvarchar(100) NULL,
	w_coname7 nvarchar(90) NULL,
	w_xmid7 char(10) NULL,
	w_programer7 nvarchar(90) NULL,
	w_remark7 nvarchar(100) NULL,
	w_coname8 nvarchar(90) NULL,
	w_xmid8 char(10) NULL,
	w_programer8 nvarchar(90) NULL,
	w_remark8 nvarchar(100) NULL,
	w_coname9 nvarchar(90) NULL,
	w_xmid9 char(10) NULL,
	w_programer9 nvarchar(90) NULL,
	w_remark9 nvarchar(100) NULL,
	w_jh ntext NULL,
	w_spman char(20) NULL,
	w_states char(20) NULL,
	w_spyj nvarchar(200) NULL,
	in_no int NULL,
	m_ps nvarchar(350) NULL
)

CREATE TABLE workreport(
	id int IDENTITY(1,1) NOT NULL,
	w_menber nvarchar(25) NOT NULL,
	w_datetime datetime NULL,
	w_man nvarchar(15) NULL,
	w_dept varchar(50) NULL,
	w_deptjb char(10) NULL,
	w_saleje decimal(18, 2) NULL,
	w_coname varchar(500) NULL,
	w_product nvarchar(500) NULL,
	sdate char(10) NULL,
	edate char(10) NULL,
	w_gz nvarchar(200) NULL,
	w_remark nvarchar(100) NULL,
	w_coname2 varchar(100) NULL,
	w_product2 nvarchar(100) NULL,
	sdate2 char(10) NULL,
	edate2 char(10) NULL,
	w_gz2 nvarchar(200) NULL,
	w_remark2 nvarchar(100) NULL,
	w_coname3 varchar(100) NULL,
	w_product3 nvarchar(100) NULL,
	sdate3 char(10) NULL,
	edate3 char(10) NULL,
	w_gz3 nvarchar(200) NULL,
	w_remark3 nvarchar(100) NULL,
	w_coname4 varchar(100) NULL,
	w_product4 nvarchar(100) NULL,
	sdate4 char(10) NULL,
	edate4 char(10) NULL,
	w_gz4 nvarchar(200) NULL,
	w_remark4 nvarchar(100) NULL,
	w_coname5 varchar(100) NULL,
	w_product5 nvarchar(100) NULL,
	sdate5 char(10) NULL,
	edate5 char(10) NULL,
	w_gz5 nvarchar(200) NULL,
	w_remark5 nvarchar(100) NULL,
	zd_gz1 nvarchar(200) NULL,
	fdate1 char(10) NULL,
	f_gz1 nvarchar(50) NULL,
	w_remark6 nvarchar(150) NULL,
	zd_gz2 nvarchar(200) NULL,
	fdate2 char(10) NULL,
	f_gz2 nvarchar(50) NULL,
	w_remark7 nvarchar(150) NULL,
	zd_gz3 nvarchar(200) NULL,
	fdate3 char(10) NULL,
	f_gz3 nvarchar(50) NULL,
	w_remark8 nvarchar(150) NULL,
	zd_gz4 nvarchar(200) NULL,
	fdate4 char(10) NULL,
	f_gz4 nvarchar(50) NULL,
	w_remark9 nvarchar(150) NULL,
	zd_gz5 nvarchar(200) NULL,
	fdate5 char(10) NULL,
	f_gz5 nvarchar(50) NULL,
	w_remark10 nvarchar(150) NULL,
	w_jh text NULL,
	w_spman char(20) NULL,
	w_states char(20) NULL,
	w_spyj nvarchar(200) NULL,
	in_no int NULL,
	m_ps nvarchar(350) NULL
)

CREATE TABLE work_report_rd(
	id int IDENTITY(1,1) NOT NULL,
	w_menber nvarchar(25) NOT NULL,
	w_datetime datetime NULL,
	w_man nvarchar(15) NULL,
	w_dept varchar(50) NULL,
	w_deptjb char(10) NULL,
	w_coname nvarchar(90) NULL,
	w_xmid char(10) NULL,
	w_programer nvarchar(90) NULL,
	w_remark nvarchar(100) NULL,
	w_coname1 nvarchar(90) NULL,
	w_xmid1 char(10) NULL,
	w_programer1 nvarchar(90) NULL,
	w_remark1 nvarchar(100) NULL,
	w_coname2 nvarchar(90) NULL,
	w_xmid2 char(10) NULL,
	w_programer2 nvarchar(90) NULL,
	w_remark2 nvarchar(100) NULL,
	w_coname3 nvarchar(90) NULL,
	w_xmid3 char(10) NULL,
	w_programer3 nvarchar(90) NULL,
	w_remark3 nvarchar(100) NULL,
	w_coname4 nvarchar(90) NULL,
	w_xmid4 char(10) NULL,
	w_programer4 nvarchar(90) NULL,
	w_remark4 nvarchar(100) NULL,
	w_jh ntext NULL,
	w_spman char(20) NULL,
	w_states char(20) NULL,
	w_spyj nvarchar(200) NULL,
	in_no int NULL,
	m_ps nvarchar(350) NULL
)

CREATE TABLE procure(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	man varchar(30) NULL,
	sub nvarchar(60) NULL,
	subck nvarchar(50) NULL,
	co_number char(30) NULL,
	coname varchar(60) NULL,
	senddate varchar(90) NULL,
	pay_if nvarchar(90) NULL,
	pay_je decimal(18, 2) NULL,
	datetime varchar(60) NULL,
	money char(15) NULL,
	tbyq ntext NULL,
	remarks ntext NULL,
	l_spqk varchar(50) NULL,
	l_spman char(15) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	l_spyj nvarchar(200) NULL,
	l_dept nvarchar(60) NULL,
	l_deptjb char(10) NULL,
	in_no int NULL,
	ponum varchar(50) NULL,
	lxr nvarchar(50) NULL,
	receiver varchar(50) NULL,
	receiver_tel varchar(50) NULL,
	receiver_addr varchar(300) NULL,
	freight varchar(50) NULL,
	express_company varchar(50) NULL,
	acct varchar(50) NULL,
	service_type varchar(50) NULL,
	pay_type varchar(50) NULL,
	coaddr varchar(350) NULL,
	cotel varchar(350) NULL,
	cofax varchar(350) NULL,
	rate varchar(350) NULL,
	self_carry int NULL,
	yfmoney varchar(50) NULL,
	jydd varchar(50) NULL,
	thremark varchar(500) NULL
)

CREATE TABLE lending_m(
	id int IDENTITY(1,1) NOT NULL,
	l_menber nvarchar(25) NOT NULL,
	l_man nvarchar(25) NULL,
	l_topic nvarchar(80) NULL,
	l_dept char(50) NULL,
	l_deptjb char(10) NULL,
	l_date datetime NULL,
	l_sqje decimal(18, 2) NOT NULL,
	l_purpose nvarchar(300) NULL,
	l_spqk nvarchar(70) NULL,
	l_spyj nvarchar(70) NULL,
	l_fqr nvarchar(25) NULL,
	remarks ntext NULL,
	expect_return_date datetime NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL
)

CREATE TABLE lending(
	id int IDENTITY(1,1) NOT NULL,
	l_menber nvarchar(25) NOT NULL,
	l_man nvarchar(25) NULL,
	l_topic nvarchar(80) NULL,
	l_dept char(50) NULL,
	l_deptjb char(10) NULL,
	l_date datetime NULL,
	l_coname nvarchar(80) NULL,
	l_sqje decimal(18, 2) NOT NULL,
	l_purpose nvarchar(300) NULL,
	l_spqk nvarchar(70) NOT NULL,
	l_spyj nvarchar(70) NULL,
	l_fqr nvarchar(25) NULL,
	remarks ntext NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL,
	man varchar(80)
)

CREATE TABLE payment_sp(
	id int IDENTITY(1,1) NOT NULL,
	p_menber nvarchar(50) NOT NULL,
	p_datetime datetime NULL,
	p_man nvarchar(20) NULL,
	p_dept nvarchar(50) NULL,
	p_deptjb char(10) NULL,
	p_company nvarchar(100) NULL,
	p_banknumber nvarchar(50) NULL,
	p_bankname nvarchar(80) NULL,
	p_payment nvarchar(30) NULL,
	p_je varchar(50) NULL,
	p_hb varchar(10) NULL,
	p_sm nvarchar(50) NULL,
	p_states nvarchar(50) NULL,
	p_spman char(10) NULL,
	fif char(10) NULL,
	fspman char(10) NULL,
	firspif char(10) NULL,
	firspman char(10) NULL,
	fourspif char(10) NULL,
	fourspman char(10) NULL,
	spyj nvarchar(300) NULL,
	in_no int NULL
)

CREATE TABLE pub_table(
	id int IDENTITY(1,1) NOT NULL,
	titel nvarchar(150) NULL,
	content ntext NULL,
	username nvarchar(50) NULL,
	fvdate nvarchar(50) NULL,
	dept nvarchar(50) NULL,
	datet int NULL,
	view_date datetime NULL,
	spman char(10) NULL,
	states char(15) NULL
)

CREATE TABLE warehouse(
	id int IDENTITY(1,1) NOT NULL,
	pro_model varchar(90) NOT NULL,
	pro_gg nvarchar(50) NULL,
	pro_name nvarchar(80) NULL,
	pro_number varchar(60) NULL,
	pro_type varchar(70) NULL,
	saleprice decimal(18, 6) NULL,
	price_hb char(10) NULL,
	pro_s_num decimal(10, 0) NULL,
	pro_num decimal(10, 0) NULL,
	pro_unit varchar(20) NULL,
	pro_price decimal(18, 6) NULL,
	pro_supplier varchar(90) NULL,
	pro_addr varchar(60) NULL,
	pro_remark varchar(400) NULL,
	sjnum nvarchar(50) NULL,
	yqnum nvarchar(50) NULL,
	yqdate nvarchar(90) NULL,
	pro_secid nvarchar(50) NULL,
	pro_sup_number char(30) NULL,
	pro_min_num int NULL,
	pro_max_num int NULL,
	sale_states char(30) NULL,
	sale_min_price nvarchar(50) NULL,
	sale_max_price nvarchar(50) NULL,
	pro_date char(30) NULL,
	pro_man char(10) NULL,
	pro_ms ntext NULL,
	pro_jstx ntext NULL,
	pro_yyfw ntext NULL,
	pin int NULL,
	js_price decimal(18, 2) NULL,
	zk_price decimal(18, 2) NULL,
	th_number varchar(50) NULL,
	pro_weight_unit varchar(50) NULL,
	batch_no varchar(50) NULL,
	finishStoking int NULL
)

CREATE TABLE work_report_r(
	id int IDENTITY(1,1) NOT NULL,
	w_menber nvarchar(25) NULL,
	w_datetime datetime NULL,
	w_man nvarchar(15) NULL,
	w_dept varchar(50) NULL,
	w_deptjb char(10) NULL,
	w_year char(4) NULL,
	w_month char(4) NULL,
	w_saleje decimal(18, 2) NULL,
	w_topic nvarchar(300) NULL,
	r_topic varchar(300) NULL,
	w_xmgz nvarchar(500) NULL,
	w_jzxx nvarchar(360) NULL,
	w_jy nvarchar(330) NULL,
	w_ktzk nvarchar(450) NULL,
	w_njy nvarchar(300) NULL,
	w_jh ntext NULL,
	w_spman char(20) NULL,
	w_states char(20) NULL,
	w_spyj nvarchar(200) NULL,
	in_no int NULL,
	m_ps nvarchar(350) NULL
)

CREATE TABLE workm(
	id int IDENTITY(1,1) NOT NULL,
	rwnumber nvarchar(20) NULL,
	rwdate datetime NULL,
	fdate datetime NULL,
	rwcontent nvarchar(80) NULL,
	rwnr nvarchar(500) NULL,
	rwzman nvarchar(30) NULL,
	rwman nvarchar(80) NULL,
	rwgman nvarchar(120) NULL,
	man nvarchar(50) NULL,
	remark ntext NULL,
	states nvarchar(25) NULL,
	sfdate datetime NULL,
	rwjg nvarchar(300) NULL,
	dept nvarchar(50) NULL,
	deptjb nvarchar(50) NULL
);

CREATE TABLE role(
	id int IDENTITY(1,1) NOT NULL,
	role_name nvarchar(50) NULL,
	remark nvarchar(200) NULL,
	role_date datetime NULL
)

CREATE TABLE profl(
	id int IDENTITY(1,1) NOT NULL,
	number char(2) NOT NULL,
	proflname nvarchar(80) NULL,
	cpro varchar(80) NULL,
	remark nvarchar(300) NULL
)

CREATE TABLE ht_mb(
	id int IDENTITY(1,1) NOT NULL,
	template_type varchar(32),
	q_name nvarchar(50) NULL,
	q_topic varchar(100) NULL,
	q_company varchar(80) NULL,
	q_addr varchar(100) NULL,
	q_man nvarchar(50) NULL,
	q_tel varchar(60) NULL,
	q_fax varchar(80) NULL,
	q_email varchar(100) NULL,
	q_net varchar(100) NULL,
	q_post nvarchar(50) NULL,
	q_number nvarchar(50) NULL,
	q_tk ntext NULL,
	remark ntext NULL,
	q_date datetime NOT NULL,
	dept varchar(50) NULL
)

drop table if exists company;

CREATE TABLE company(
	id int IDENTITY(1,1) NOT NULL,
	companyname varchar(150) NULL,
	companyname2 varchar(150) NULL,
	companyaddr varchar(150) NULL,
	companyaddr2 varchar(150) NULL,
	companytel varchar(100) NULL,
	companyfax varchar(100) NULL,
	companybank varchar(100) NULL,
	companybank2 varchar(100) NULL,
	bank_dm varchar(100) NULL,
	bank_dm2 varchar(100) NULL,
	companynumber varchar(100) NULL,
	companynumber2 varchar(100) NULL,
	com_bank_code varchar(120) NULL,
	com_bank_code2 varchar(120) NULL,
	com_sy_code varchar(120) NULL,
	com_sy_code2 varchar(120) NULL,
	com_sy_name varchar(120) NULL,
	com_sy_name2 varchar(120) NULL,
	bankroll varchar(50) NULL,
	companyman varchar(50) NULL,
	companydm varchar(50) NULL,
	companysh varchar(50) NULL,
	companybm varchar(50) NULL,
	companylxr varchar(50) NULL,
	companyemail varchar(50) NULL,
	companynet varchar(50) NULL,
	username varchar(50) NULL,
	datetime varchar(50) NULL,
	remark varchar(1000) NULL,
	picpath varchar(50) NULL,
	disyz varchar(50),
	type varchar(50) NULL,
	pic_id varchar(50)
	
)

CREATE TABLE supplier(
	id int IDENTITY(1,1) NOT NULL,
	co_number char(30) NOT NULL,
	coname varchar(150) NOT NULL,
	coaddr varchar(150) NULL,
	copost varchar(50) NULL,
	city varchar(50) NULL,
	country varchar(50) NULL,
	province varchar(50) NULL,
	cofrdb varchar(50) NULL,
	cozzxs varchar(50) NULL,
	cozczb varchar(50) NULL,
	coyyzz varchar(50) NULL,
	cotypes varchar(50) NULL,
	tradetypes nvarchar(50) NULL,
	cokhjb varchar(50) NULL,
	cokhyh varchar(150) NULL,
	coyhzh varchar(50) NULL,
	coclrq varchar(50) NULL,
	ifjckq varchar(50) NULL,
	cotel varchar(50) NULL,
	cofax varchar(50) NULL,
	codzyj varchar(50) NULL,
	conet varchar(50) NULL,
	cosyhb varchar(50) NULL,
	cojsfs varchar(50) NULL,
	nshm varchar(50) NULL,
	number varchar(50) NULL,
	username varchar(50) NULL,
	dept varchar(50) NULL,
	deptjb char(10) NULL,
	modman varchar(50) NULL,
	mod_date varchar(50) NULL,
	share varchar(50) NULL,
	yearearning varchar(50) NULL,
	valueco nvarchar(50) NULL,
	rg_date nvarchar(50) NULL,
	annual_sales nvarchar(200) NULL,
	sales_ability nvarchar(200) NULL,
	qlty_control nvarchar(200) NULL,
	companymt nvarchar(200) NULL,
	scale nvarchar(4000) NULL,
	warehouse nvarchar(200) NULL,
	describee nvarchar(4000) NULL,
	in_no int NULL,
	certification varchar(30) NULL,
	bank_addr ntext NULL,
	swift_code varchar(50) NULL,
	iban varchar(50) NULL,
	route varchar(50) NULL,
	bic varchar(50) NULL,
	receiver varchar(50) NULL,
	receiver_tel varchar(50) NULL,
	receiver_addr varchar(50) NULL,
	freight varchar(50) NULL,
	express_company varchar(50) NULL,
	acct varchar(50) NULL,
	service_type varchar(50) NULL,
	pay_type varchar(50) NULL,
	pf float NULL
)

CREATE TABLE restrain_name(
	id int IDENTITY(1,1) NOT NULL,
	r_name char(35) NOT NULL,
	dept nvarchar(90) NULL,
	deptjb char(10) NULL,
	qzmod char(10) NULL,
	qzdel char(10) NULL,
	qzview char(10) NULL,
	qzview_yes char(10) NULL,
	qzzt char(10) NULL,
	xhadd char(10) NULL,
	xhmod char(10) NULL,
	xhdel char(10) NULL,
	xhview char(10) NULL,
	xhview_yes char(10) NULL,
	xhzt char(10) NULL,
	linkadd char(10) NULL,
	linkmod char(10) NULL,
	linkdel char(10) NULL,
	linkview char(10) NULL,
	linkview_yes char(10) NULL,
	linkzt char(10) NULL,
	hzadd char(10) NULL,
	hzmod char(10) NULL,
	hzdel char(10) NULL,
	hzview char(10) NULL,
	hzview_yes char(10) NULL,
	hzzt char(10) NULL,
	supadd char(10) NULL,
	supmod char(10) NULL,
	supdel char(10) NULL,
	supview char(10) NULL,
	supview_yes char(10) NULL,
	supzt char(10) NULL,
	actadd char(10) NULL,
	actmod char(10) NULL,
	actdel char(10) NULL,
	actview char(10) NULL,
	actview_yes char(10) NULL,
	actzt char(10) NULL,
	opadd char(10) NULL,
	opmod char(10) NULL,
	opdel char(10) NULL,
	opview char(10) NULL,
	opview_yes char(10) NULL,
	opzt char(10) NULL,
	quoteadd char(10) NULL,
	quotemod char(10) NULL,
	quotedel char(10) NULL,
	quoteview char(10) NULL,
	quoteview_yes char(10) NULL,
	quotezt char(10) NULL,
	profl nvarchar(100) NULL,
	proadd char(10) NULL,
	promod char(10) NULL,
	prodel char(10) NULL,
	proview char(10) NULL,
	proview_yes char(10) NULL,
	prozt char(10) NULL,
	cgadd char(10) NULL,
	cgmod char(10) NULL,
	cgdel char(10) NULL,
	cgview char(10) NULL,
	cgview_yes char(10) NULL,
	cgzt char(10) NULL,
	tradd char(10) NULL,
	trmod char(10) NULL,
	trdel char(10) NULL,
	trview char(10) NULL,
	trview_yes char(10) NULL,
	trzt char(10) NULL,
	hdadd char(10) NULL,
	hdmod char(10) NULL,
	hddel char(10) NULL,
	hdview char(10) NULL,
	hdview_yes char(10) NULL,
	hdzt char(10) NULL,
	r_yfgladd char(10) NULL,
	r_yfglmod char(10) NULL,
	r_yfgldel char(10) NULL,
	r_yfglview char(10) NULL,
	r_yfglview_yes char(10) NULL,
	r_yfglzt char(10) NULL,
	workadd char(10) NULL,
	workmod char(10) NULL,
	workdel char(10) NULL,
	workview char(10) NULL,
	workview_yes char(10) NULL,
	workzt char(10) NULL,
	r_month_jh_add char(10) NULL,
	r_month_jh_mod char(10) NULL,
	r_month_jh_del char(10) NULL,
	r_month_jh_view char(10) NULL,
	r_month_jh_view_yes char(10) NULL,
	r_month_jh_zt char(10) NULL,
	r_date_r_add char(10) NULL,
	r_date_r_mod char(10) NULL,
	r_date_r_del char(10) NULL,
	r_date_r_view char(10) NULL,
	r_date_r_view_yes char(10) NULL,
	r_date_r_zt char(10) NULL,
	r_week_r_add char(10) NULL,
	r_week_r_mod char(10) NULL,
	r_week_r_del char(10) NULL,
	r_week_r_view char(10) NULL,
	r_week_r_view_yes char(10) NULL,
	r_week_r_zt char(10) NULL,
	r_month_r_add char(10) NULL,
	r_month_r_mod char(10) NULL,
	r_month_r_del char(10) NULL,
	r_month_r_view char(10) NULL,
	r_month_r_view_yes char(10) NULL,
	r_month_r_zt char(10) NULL,
	xmadd char(10) NULL,
	xmmod char(10) NULL,
	xmdel char(10) NULL,
	xmview char(10) NULL,
	xmview_yes char(10) NULL,
	xmzt char(10) NULL,
	r_htgl_add char(10) NULL,
	r_htgl_mod char(10) NULL,
	r_htgl_del char(10) NULL,
	r_htgl_view char(10) NULL,
	r_htgl_view_yes char(10) NULL,
	r_htgl_zt char(10) NULL,
	subadd char(10) NULL,
	submod char(10) NULL,
	subdel char(10) NULL,
	subview char(10) NULL,
	subview_yes char(10) NULL,
	subzt char(10) NULL,
	manadd char(10) NULL,
	manmod char(10) NULL,
	mandel char(10) NULL,
	manview char(10) NULL,
	manview_yes char(10) NULL,
	manzt char(10) NULL,
	rwadd char(10) NULL,
	rwmod char(10) NULL,
	rwdel char(10) NULL,
	rwview char(10) NULL,
	rwview_yes char(10) NULL,
	rwzt char(10) NULL,
	fyadd char(10) NULL,
	fymod char(10) NULL,
	fydel char(10) NULL,
	fyview char(10) NULL,
	fyview_yes char(10) NULL,
	fyzt char(10) NULL,
	r_jkgl_add char(10) NULL,
	r_jkgl_mod char(10) NULL,
	r_jkgl_del char(10) NULL,
	r_jkgl_view char(10) NULL,
	r_jkgl_view_yes char(10) NULL,
	r_jkgl_zt char(10) NULL,
	r_fksq_add char(10) NULL,
	r_fksq_mod char(10) NULL,
	r_fksq_del char(10) NULL,
	r_fksq_view char(10) NULL,
	r_fksq_view_yes char(10) NULL,
	r_fksq_zt char(10) NULL,
	thadd char(10) NULL,
	thmod char(10) NULL,
	thdel char(10) NULL,
	thview char(10) NULL,
	thview_yes char(10) NULL,
	thzt char(10) NULL,
	serveradd char(10) NULL,
	servermod char(10) NULL,
	serverdel char(10) NULL,
	serverview char(10) NULL,
	serverview_yes char(10) NULL,
	serverzt char(10) NULL,
	tsadd char(10) NULL,
	tsmod char(10) NULL,
	tsdel char(10) NULL,
	tsview char(10) NULL,
	tsview_yes char(10) NULL,
	tszt char(10) NULL,
	wxadd char(10) NULL,
	wxmod char(10) NULL,
	wxdel char(10) NULL,
	wxview char(10) NULL,
	wxview_yes char(10) NULL,
	wxzt char(10) NULL,
	r_hyzc_add char(10) NULL,
	r_hyzc_mod char(10) NULL,
	r_hyzc_del char(10) NULL,
	r_hyzc_view char(10) NULL,
	r_hyzc_view_yes char(10) NULL,
	r_hyzc_zt char(10) NULL,
	r_mtxc_add char(10) NULL,
	r_mtxc_mod char(10) NULL,
	r_mtxc_del char(10) NULL,
	r_mtxc_view char(10) NULL,
	r_mtxc_view_yes char(10) NULL,
	r_mtxc_zt char(10) NULL,
	mactadd char(10) NULL,
	mactmod char(10) NULL,
	mactdel char(10) NULL,
	mactview char(10) NULL,
	mactview_yes char(10) NULL,
	mactzt char(10) NULL,
	jzdsadd char(10) NULL,
	jzdsmod char(10) NULL,
	jzdsdel char(10) NULL,
	jzdsview char(10) NULL,
	jzdsview_yes char(10) NULL,
	jzdszt char(10) NULL,
	zskadd char(10) NULL,
	zskmod char(10) NULL,
	zskdel char(10) NULL,
	zskview char(10) NULL,
	zskview_yes char(10) NULL,
	zskzt char(10) NULL,
	flfgadd char(10) NULL,
	flfgmod char(10) NULL,
	flfgdel char(10) NULL,
	flfgview char(10) NULL,
	flfgview_yes char(10) NULL,
	flfgzt char(10) NULL,
	r_wlz_add char(10) NULL,
	r_wlz_mod char(10) NULL,
	r_wlz_del char(10) NULL,
	r_wlz_view char(10) NULL,
	r_wlz_view_yes char(10) NULL,
	r_wlz_zt char(10) NULL,
	zjadd char(10) NULL,
	zjmod char(10) NULL,
	zjdel char(10) NULL,
	zjview char(10) NULL,
	zjview_yes char(10) NULL,
	zjzt char(10) NULL,
	fkhzadd char(10) NULL,
	fkhzmod char(10) NULL,
	fkhzdel char(10) NULL,
	fkhzview char(10) NULL,
	fkhzview_yes char(10) NULL,
	fkhzzt char(10) NULL,
	skhzadd char(10) NULL,
	skhzmod char(10) NULL,
	skhzdel char(10) NULL,
	skhzview char(10) NULL,
	skhzview_yes char(10) NULL,
	skhzzt char(10) NULL,
	fkmod char(10) NULL,
	fkdel char(10) NULL,
	fkview char(10) NULL,
	fkview_yes char(10) NULL,
	fkzt char(10) NULL,
	skmod char(10) NULL,
	skdel char(10) NULL,
	skview char(10) NULL,
	skview_yes char(10) NULL,
	skzt char(10) NULL,
	qkmod char(10) NULL,
	qkdel char(10) NULL,
	qkview char(10) NULL,
	qkview_yes char(10) NULL,
	qkzt char(10) NULL,
	r_thje_mod char(10) NULL,
	r_thje_del char(10) NULL,
	r_thje_view char(10) NULL,
	r_thje_view_yes char(10) NULL,
	r_thje_zt char(10) NULL,
	intadd char(10) NULL,
	intmod char(10) NULL,
	intdel char(10) NULL,
	intview char(10) NULL,
	intview_yes char(10) NULL,
	intzt char(10) NULL,
	outadd char(10) NULL,
	outmod char(10) NULL,
	outdel char(10) NULL,
	outview char(10) NULL,
	outview_yes char(10) NULL,
	outzt char(10) NULL,
	r_dzzx_zt char(10) NULL,
	r_xscp_zt char(10) NULL,
	syszt char(10) NULL,
	jcfxzt char(10) NULL,
	custzyzt char(10) NULL
)

CREATE TABLE country(
	id int IDENTITY(1,1) NOT NULL,
	coun_name nvarchar(100) NOT NULL
);

CREATE TABLE province(
	id int IDENTITY(1,1) NOT NULL,
	province_name varchar(100) NULL,
	province_num char(3) NULL
);

CREATE TABLE city(
	id int IDENTITY(1,1) NOT NULL,
	province nvarchar(100) NULL,
	city_name nvarchar(100) NULL,
	provinceId int
);

CREATE TABLE hltable(
	id int IDENTITY(1,1) NOT NULL,
	currname nvarchar(80) NOT NULL,
	currrate decimal(18, 5) NULL,
	creatdate nvarchar(20) NULL
)

CREATE TABLE payment_fs(
	id int IDENTITY(1,1) NOT NULL,
	payment varchar(50) NOT NULL,
	remark varchar(300) NULL,
	pay_date datetime NOT NULL
)

CREATE TABLE payway_cg(
	id int IDENTITY(1,1) NOT NULL,
	payment varchar(50) NOT NULL,
	remark varchar(300) NULL,
	pay_date datetime NOT NULL
)

CREATE TABLE cgsp(
	id int IDENTITY(1,1) NOT NULL,
	dept char(30) NULL,
	role char(15) NULL,
	price_min decimal(18, 2) NULL,
	price_max decimal(18, 2) NULL,
	dd_man char(15) NOT NULL,
	fif char(10) NOT NULL,
	fspman varchar(50) NOT NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL
)

CREATE TABLE client(
	clientid int IDENTITY(1,1) NOT NULL,
	co_number char(15) NOT NULL,
	coname varchar(150) NOT NULL,
	coaddr varchar(160) NULL,
	copost varchar(50) NULL,
	city varchar(50) NULL,
	province varchar(50) NULL,
	cofrdb varchar(50) NULL,
	cozzxs varchar(50) NULL,
	cozczb varchar(50) NULL,
	coyyzz varchar(50) NULL,
	cotypes varchar(50) NULL,
	tradetypes nvarchar(50) NULL,
	cokhjb varchar(50) NULL,
	cokhyh varchar(150) NULL,
	coyhzh varchar(50) NULL,
	coclrq varchar(50) NULL,
	cotel varchar(50) NULL,
	cofax varchar(50) NULL,
	codzyj varchar(50) NULL,
	conet varchar(50) NULL,
	cosyhb varchar(50) NULL,
	cojsfs varchar(50) NULL,
	link_zw1 char(30) NULL,
	paydate nvarchar(50) NULL,
	link_wap1 char(30) NULL,
	link_mail1 nvarchar(90) NULL,
	linkman2 char(50) NULL,
	link_zw2 char(30) NULL,
	link_tel2 nvarchar(50) NULL,
	link_wap2 char(30) NULL,
	link_mail2 nvarchar(90) NULL,
	linkman3 char(50) NULL,
	link_zw3 char(30) NULL,
	link_tel3 nvarchar(50) NULL,
	link_wap3 char(30) NULL,
	link_mail3 nvarchar(90) NULL,
	linkman4 char(50) NULL,
	link_zw4 char(30) NULL,
	link_tel4 nvarchar(50) NULL,
	link_wap4 char(30) NULL,
	link_mail4 nvarchar(90) NULL,
	linkman5 char(50) NULL,
	link_zw5 char(30) NULL,
	link_tel5 nvarchar(50) NULL,
	link_wap5 char(30) NULL,
	link_mail5 nvarchar(90) NULL,
	limited_credit nvarchar(50) NULL,
	rg_date datetime NULL,
	nsnumber nvarchar(50) NULL,
	number varchar(50) NULL,
	yearearning varchar(50) NULL,
	username varchar(50) NULL,
	dept nvarchar(50) NULL,
	deptjb char(30) NULL,
	modman char(10) NULL,
	mod_date datetime NULL,
	share varchar(50) NULL,
	mproduct varchar(1000) NULL,
	product nvarchar(260) NULL,
	company_management varchar(360) NULL,
	describee ntext NULL,
	in_no int NULL,
	co_code char(10) NULL,
	bank_name ntext NULL,
	bank_addr ntext NULL,
	swift_code varchar(50) NULL,
	iban varchar(50) NULL,
	route varchar(50) NULL,
	bic varchar(50) NULL,
	follower varchar(50),
	pay_deadline int
)

CREATE TABLE hylxtable(
	id int IDENTITY(1,1) NOT NULL,
	hyname nvarchar(50) NULL
)

CREATE TABLE xyjb(
	id int IDENTITY(1,1) NOT NULL,
	xyjb_name varchar(50) NOT NULL,
	remark varchar(300) NULL,
	xy_date datetime NOT NULL
)

CREATE TABLE htsp(
	id int IDENTITY(1,1) NOT NULL,
	dept char(30) NULL,
	role char(15) NULL,
	ifsp char(10) NULL,
	dd_man char(15) NOT NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL
)

CREATE TABLE ddsp(
	id int IDENTITY(1,1) NOT NULL,
	dept nvarchar(50) NULL,
	role char(15) NULL,
	price_min decimal(18, 0) NULL,
	price_max decimal(18, 0) NULL,
	if_sp char(10) NULL,
	dd_man char(15) NOT NULL,
	fif char(10) NOT NULL,
	fspman varchar(50) NOT NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL
)

CREATE TABLE ddpro(
	id int IDENTITY(1,1) NOT NULL,
	ddid varchar(50) NOT NULL,
	epro varchar(150) NOT NULL,
	num int NOT NULL,
	fypronum varchar(50) NULL,
	unit varchar(50) NULL,
	cpro varchar(150) NULL,
	rale_types varchar(50) NULL,
	rale decimal(10, 2) NULL,
	supplier varchar(150) NULL,
	pricehb nvarchar(30) NOT NULL,
	salejg decimal(18, 6) NOT NULL,
	selljg decimal(18, 6) NULL,
	money varchar(50) NULL,
	fyproall char(55) NULL,
	wid nvarchar(90) NULL,
	x_no nvarchar(90) NULL,
	remark nvarchar(350) NULL,
	s_num int NULL,
	s_c_num int NULL,
	s_tr_date char(15) NULL,
	fy_states char(10) NULL,
	p_check nvarchar(150) NULL,
	money2 decimal(18, 6) NULL,
	mpn varchar(50) NULL,
	pro_jz varchar(50) NULL,
	pro_mz varchar(50) NULL,
	pro_cc varchar(50) NULL,
	pro_cd varchar(50) NULL,
	th_num int NULL,
	hl varchar(50) NULL
)

CREATE TABLE payment(
	id int IDENTITY(1,1) NOT NULL,
	contract varchar(50) NOT NULL,
	orderform varchar(50) NULL,
	sup_number char(30) NULL,
	supplier nvarchar(100) NULL,
	pay_je nvarchar(50) NULL,
	htmoney decimal(18, 1) NULL,
	yjfkdate varchar(50) NULL,
	sjfkdate varchar(50) NULL,
	moneytypes varchar(50) NULL,
	note varchar(50) NULL,
	bank varchar(150) NULL,
	bankaccounts decimal(18, 2) NULL,
	moneyty varchar(50) NULL,
	wtfk varchar(10) NULL,
	paynr nvarchar(300) NULL,
	remark varchar(50) NULL,
	states nvarchar(50) NULL,
	skfs varchar(50) NULL
)

CREATE TABLE gathering_customer(
	id int IDENTITY(1,1) NOT NULL,
	coname nvarchar(100) NULL,
	coaddr nvarchar(100) NULL,
	cofrdb nvarchar(50) NULL,
	cotel nvarchar(50) NULL,
	cofax nvarchar(50) NULL,
	bank nvarchar(100) NULL,
	payment_je decimal(18, 4) NULL,
	payment_sje decimal(18, 4) NULL,
	money char(10) NULL,
	remark ntext NULL,
	payment_date datetime NULL,
	co_number nvarchar(50) NULL,
	dept nvarchar(90) NULL,
	deptjb char(20) NULL,
	pname char(15) NULL
)

CREATE TABLE cgpro(
	id int IDENTITY(1,1) NOT NULL,
	ddid varchar(10) NOT NULL,
	epro varchar(80) NOT NULL,
	cpro nvarchar(100) NULL,
	pro_number nvarchar(50) NULL,
	num int NOT NULL,
	unit varchar(50) NULL,
	selljg decimal(18, 6) NULL,
	money varchar(50) NULL,
	cgpro_ydatetime nvarchar(50) NULL,
	cgpro_num int NOT NULL,
	cgpro_sdatetime nvarchar(30) NULL,
	remark nvarchar(300) NULL,
	supplier nvarchar(50) NULL,
	rate int NULL,
	wid nvarchar(90) NULL,
	sale_supplier varchar(50) NULL,
	sale_remark varchar(350) NULL,
	sale_rate varchar(50) NULL,
	sale_finance varchar(50) NULL,
	sale_pro_id int
)

CREATE TABLE punit_type(
	id int IDENTITY(1,1) NOT NULL,
	punit_name nvarchar(20) NOT NULL
) 

CREATE TABLE pf_supplier(
	id int IDENTITY(1,1) NOT NULL,
	co_number varchar(30) NULL,
	username varchar(30) NULL,
	rfq float NULL,
	bj float NULL,
	ch float NULL,
	fh float NULL,
	th float NULL,
	remark ntext NULL,
	pf_datetime datetime NULL
)

CREATE TABLE sample_dh(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	man varchar(30) NOT NULL,
	sub nvarchar(60) NULL,
	coname varchar(60) NOT NULL,
	yj varchar(50) NOT NULL,
	money nvarchar(50) NOT NULL,
	habitus varchar(10) NOT NULL,
	datetime datetime NOT NULL,
	senddate nvarchar(100) NULL,
	delivery_terms nvarchar(200) NULL,
	delivery_date nvarchar(200) NULL,
	airport varchar(200) NULL,
	tbyq nvarchar(200) NULL,
	remarks text NULL,
	state varchar(50) NOT NULL,
	spman varchar(50) NULL,
	spdate nvarchar(50) NULL,
	spyj nvarchar(300) NULL,
	fif char(10) NULL,
	cwman char(15) NULL,
	cwdate nvarchar(50) NULL,
	cwyj varchar(300) NULL,
	dept char(30) NULL,
	deptjb char(10) NULL,
	linkman nvarchar(50) NULL,
	fveight nvarchar(50) NULL,
	insurance decimal(18, 2) NULL,
	in_no int NULL,
	syyj nvarchar(200) NULL
)

CREATE TABLE th_table_supplier(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	man varchar(30) NOT NULL,
	xiaoshou nvarchar(60) NULL,
	sub nvarchar(60) NULL,
	coname varchar(60) NOT NULL,
	co_number nvarchar(20) NULL,
	money char(10) NOT NULL,
	habitus varchar(10) NOT NULL,
	datetime datetime NOT NULL,
	remarks nvarchar(200) NULL,
	state varchar(10) NOT NULL,
	spman varchar(50) NULL,
	spdate nvarchar(50) NULL,
	spyj nvarchar(300) NULL,
	fif char(10) NULL,
	cwman char(15) NULL,
	cwdate nvarchar(50) NULL,
	cwyj varchar(300) NULL,
	firspif char(10) NULL,
	firspman char(15) NULL,
	fspyj nvarchar(300) NULL,
	dept char(30) NULL,
	deptjb char(10) NULL,
	in_no int NULL,
	w_remark nvarchar(350) NULL,
	skfs varchar(50) NULL,
	colxr varchar(max) NULL,
	coaddr varchar(max) NULL,
	cotel varchar(max) NULL,
	cofax varchar(max) NULL,
	xsman varchar(50) NULL
)

CREATE TABLE in_warehouse(
	id int IDENTITY(1,1) NOT NULL,
	number nvarchar(20) NOT NULL,
	cg_number nvarchar(50) NULL,
	supplier_id int,
	supplier nvarchar(90) NULL,
	sp_number nvarchar(50) NULL,
	int_types char(15) NULL,
	money char(10) NOT NULL,
	int_date datetime NOT NULL,
	g_man char(10) NULL,
	man char(10) NOT NULL,
	dept nvarchar(50) NULL,
	deptjb char(10) NULL,
	remark ntext NULL,
	in_no int NULL,
	states char(10) NULL
)

CREATE TABLE rkhouse(
	id int IDENTITY(1,1) NOT NULL,
	pro_model nvarchar(90) NOT NULL,
	pro_name nvarchar(80) NULL,
	pro_number nvarchar(90) NULL,
	pro_num int NOT NULL,
	pro_unit varchar(20) NOT NULL,
	pro_price decimal(18, 6) NOT NULL,
	pro_hb char(10) NULL,
	pro_supplier varchar(90) NULL,
	pro_addr varchar(50) NULL,
	pro_id nvarchar(50) NOT NULL,
	pro_datetime datetime NOT NULL,
	remark varchar(300) NULL,
	pro_types nvarchar(50) NULL,
	pro_sup_number char(30) NULL,
	pro_rate char(15) NULL,
	pro_rk_num char(20) NULL,
	pro_cgy char(30) NULL,
	status int NULL
)

CREATE TABLE credit_debit(
	id int IDENTITY(1,1) NOT NULL,
	l_menber nvarchar(25) NOT NULL,
	l_man nvarchar(25) NULL,
	reference nvarchar(50) NULL,
	l_topic nvarchar(80) NULL,
	l_dept char(50) NULL,
	l_deptjb char(10) NULL,
	l_c_d nvarchar(90) NULL,
	l_date datetime NULL,
	l_coname nvarchar(90) NULL,
	co_number char(80) NULL,
	l_sqje decimal(18, 4) NOT NULL,
	l_sje decimal(18, 4) NULL,
	l_hb char(10) NULL,
	compendium nvarchar(300) NULL,
	g_bank nvarchar(300) NULL,
	g_banknum nvarchar(50) NULL,
	remarks ntext NOT NULL,
	in_no int NULL,
	st int NULL,
	sy char(10) NULL,
	km nvarchar(90) NULL,
	kms nvarchar(90) NULL,
	rale decimal(18, 5) NULL,
	states char(20) NULL,
	spman char(20) NULL,
	spdate nvarchar(50) NULL,
	spyj nvarchar(350) NULL,
	fif char(10) NULL,
	fspman char(20) NULL,
	fspdate char(20) NULL,
	fspyj nvarchar(350) NULL,
	xsdh varchar(100) NULL,
	cgdh varchar(100) NULL
)

CREATE TABLE km_mx(
	id int IDENTITY(1,1) NOT NULL,
	km nvarchar(90) NULL,
	km_mx nvarchar(80) NULL,
	kmId int NULL
)

CREATE TABLE km (
	id int IDENTITY(1,1) NOT NULL,
	coun_number char(40) NULL,
	km_fx char(10) NULL,
	coun_name nvarchar(200) NULL,
	coun_ename nvarchar(200) NULL
)

CREATE TABLE gather_mx_mx(
	id int IDENTITY(1,1) NOT NULL,
	g_m_id char(10) NOT NULL,
	g_m_types int NOT NULL,
	g_m_number char(30) NOT NULL,
	g_m_coname nvarchar(80) NOT NULL,
	g_m_smoney decimal(18, 4) NOT NULL,
	g_m_hb char(10) NULL,
	g_m_salesman char(15) NOT NULL,
	g_m_date datetime NULL,
	g_m_man char(10) NULL
)

CREATE TABLE work_report(
	id int IDENTITY(1,1) NOT NULL,
	w_menber nvarchar(25) NOT NULL,
	w_datetime datetime NULL,
	w_man nvarchar(15) NULL,
	w_dept varchar(50) NULL,
	w_deptjb char(10) NULL,
	w_saleje nvarchar(50) NULL,
	w_coname varchar(500) NULL,
	w_product nvarchar(500) NULL,
	sdate nvarchar(350) NULL,
	edate nvarchar(350) NULL,
	w_gz nvarchar(400) NULL,
	w_remark nvarchar(400) NULL,
	w_coname2 varchar(300) NULL,
	w_product2 nvarchar(400) NULL,
	sdate2 nvarchar(350) NULL,
	edate2 nvarchar(350) NULL,
	w_gz2 nvarchar(400) NULL,
	w_remark2 nvarchar(400) NULL,
	w_coname3 varchar(350) NULL,
	w_product3 nvarchar(450) NULL,
	sdate3 nvarchar(350) NULL,
	edate3 nvarchar(350) NULL,
	w_gz3 nvarchar(400) NULL,
	w_remark3 nvarchar(400) NULL,
	w_coname4 varchar(400) NULL,
	w_product4 nvarchar(400) NULL,
	sdate4 nvarchar(350) NULL,
	edate4 nvarchar(350) NULL,
	w_gz4 nvarchar(400) NULL,
	w_remark4 nvarchar(400) NULL,
	w_coname5 varchar(400) NULL,
	w_product5 nvarchar(400) NULL,
	sdate5 nvarchar(350) NULL,
	edate5 nvarchar(350) NULL,
	w_gz5 nvarchar(400) NULL,
	w_remark5 nvarchar(100) NULL,
	w_jh ntext NULL,
	w_spman char(20) NULL,
	w_states char(20) NULL,
	w_spyj nvarchar(200) NULL,
	in_no int NULL,
	m_ps nvarchar(350) NULL
)

CREATE TABLE work_report_rdm(
	id int IDENTITY(1,1) NOT NULL,
	w_menber nvarchar(25) NOT NULL,
	w_datetime datetime NULL,
	w_man nvarchar(15) NULL,
	w_dept varchar(50) NULL,
	w_deptjb char(10) NULL,
	w_a_coname ntext NULL,
	w_a_qt ntext NULL,
	w_a_remark nvarchar(450) NULL,
	w_f_coname ntext NULL,
	w_f_qt ntext NULL,
	w_f_remark nvarchar(450) NULL,
	w_jh text NULL,
	w_spman char(20) NULL,
	w_states char(20) NULL,
	w_spyj nvarchar(200) NULL,
	in_no int NULL,
	m_ps nvarchar(350) NULL
)

CREATE TABLE work_report_rm(
	id int IDENTITY(1,1) NOT NULL,
	w_menber nvarchar(25) NULL,
	w_datetime datetime NULL,
	w_man nvarchar(15) NULL,
	w_dept varchar(50) NULL,
	w_deptjb char(10) NULL,
	w_year char(4) NULL,
	w_month char(4) NULL,
	w_programer ntext NULL,
	w_progj ntext NULL,
	w_hjcs nvarchar(500) NULL,
	w_jh_gzsx nvarchar(400) NULL,
	w_jh_gznr nvarchar(450) NULL,
	w_jh_gzmb nvarchar(350) NULL,
	w_jh_lscs nvarchar(450) NULL,
	w_jh ntext NULL,
	w_spman char(20) NULL,
	w_states char(20) NULL,
	w_spyj nvarchar(200) NULL,
	in_no int NULL,
	m_ps nvarchar(350) NULL
)

CREATE TABLE month_report_rdm(
	id int IDENTITY(1,1) NOT NULL,
	w_menber nvarchar(25) NOT NULL,
	w_datetime datetime NULL,
	w_man nvarchar(15) NULL,
	w_dept varchar(50) NULL,
	w_deptjb char(10) NULL,
	w_a_coname ntext NULL,
	w_a_jh ntext NULL,
	w_a_qt ntext NULL,
	w_a_remark ntext NULL,
	w_ycqk nvarchar(450) NULL,
	w_jh ntext NULL,
	w_spman char(20) NULL,
	w_states char(20) NULL,
	w_spyj nvarchar(200) NULL,
	in_no int NULL,
	m_ps nvarchar(350) NULL
)

CREATE TABLE m_zzgl(
	id int IDENTITY(1,1) NOT NULL,
	l_menber char(20) NOT NULL,
	man char(10) NULL,
	l_man char(10) NOT NULL,
	l_dept nvarchar(80) NULL,
	l_deptjb char(10) NULL,
	l_role nvarchar(90) NULL,
	l_dg_date char(15) NULL,
	l_date datetime NOT NULL,
	l_zz_date char(15) NULL,
	l_jcyy ntext NULL,
	remarks ntext NULL,
	l_spqk nvarchar(70) NULL,
	l_spyj nvarchar(370) NULL,
	l_fqr nvarchar(25) NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL
)

CREATE TABLE m_jcgl(
	id int IDENTITY(1,1) NOT NULL,
	l_menber char(20) NOT NULL,
	l_name char(30) NULL,
	l_company nvarchar(80) NULL,
	l_role char(20) NULL,
	l_types nvarchar(50) NULL,
	l_jcyj nvarchar(150) NULL,
	l_man char(15) NULL,
	l_dept nvarchar(80) NULL,
	l_deptjb char(15) NULL,
	l_date datetime NULL,
	l_jcyy ntext NULL,
	remarks ntext NULL,
	l_spqk nvarchar(70) NULL,
	l_spyj nvarchar(370) NULL,
	l_fqr nvarchar(25) NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL
)

CREATE TABLE m_stipend(
	id int IDENTITY(1,1) NOT NULL,
	l_menber char(20) NOT NULL,
	man char(10) NULL,
	l_man char(10) NOT NULL,
	l_dept nvarchar(80) NULL,
	l_deptjb char(10) NULL,
	l_role nvarchar(90) NULL,
	l_dg_date char(15) NULL,
	l_date datetime NOT NULL,
	l_zz_date char(15) NULL,
	l_tzsx nvarchar(50) NULL,
	l_ylxz nvarchar(50) NULL,
	l_tzbl nvarchar(50) NULL,
	l_tzje nvarchar(50) NULL,
	l_tzhxz nvarchar(50) NULL,
	l_jcyy ntext NULL,
	remarks ntext NULL,
	l_spqk nvarchar(70) NULL,
	l_spyj nvarchar(370) NULL,
	l_fqr nvarchar(25) NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL
) 

CREATE TABLE m_evection(
	id int IDENTITY(1,1) NOT NULL,
	l_menber char(20) NOT NULL,
	man char(10) NULL,
	l_man char(10) NOT NULL,
	l_dept nvarchar(80) NULL,
	l_deptjb char(10) NULL,
	l_role nvarchar(90) NULL,
	l_dg_date nvarchar(350) NULL,
	l_date datetime NOT NULL,
	l_zz_date nvarchar(50) NULL,
	l_jcyy ntext NULL,
	remarks ntext NULL,
	l_spqk nvarchar(70) NULL,
	l_spyj nvarchar(370) NULL,
	l_fqr nvarchar(25) NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL
)

CREATE TABLE procure_of(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	man varchar(30) NULL,
	coname varchar(60) NULL,
	senddate varchar(90) NULL,
	pay_if nvarchar(90) NULL,
	pay_je nvarchar(90) NULL,
	datetime varchar(60) NULL,
	money char(15) NULL,
	remarks ntext NULL,
	l_spqk varchar(50) NULL,
	l_spman char(15) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	l_spyj nvarchar(200) NULL,
	l_dept nvarchar(60) NULL,
	l_deptjb char(10) NULL,
	in_no int NULL
) 

CREATE TABLE sendmail(
	id int IDENTITY(1,1) NOT NULL,
	mail_to nvarchar(100) NULL,
	mail_to2 nvarchar(100) NULL,
	mail_to3 nvarchar(100) NULL,
	mail_sub nvarchar(500) NULL,
	mail_nr ntext NULL,
	mail_man char(10) NULL,
	deptjb char(15) NULL,
	dept nvarchar(50) NULL,
	mail_datetime char(30) NULL,
	states char(10) NULL,
	form_to nvarchar(200) NULL,
	form_to2 nvarchar(200) NULL,
	form_to3 nvarchar(200) NULL
)


CREATE TABLE gathering(
	id int IDENTITY(1,1) NOT NULL,
	fyid char(50) NULL,
	invoice varchar(50) NOT NULL,
	orderform varchar(50) NOT NULL,
	imoney decimal(18, 4) NULL,
	ymoney decimal(18, 4) NULL,
	smoney decimal(18, 4) NULL,
	coname varchar(80) NULL,
	bank decimal(18, 4) NULL,
	bankaccounts varchar(80) NULL,
	yjskdate varchar(30) NULL,
	sjdate varchar(30) NULL,
	sjskdate datetime NULL,
	skdate char(15) NULL,
	mode varchar(80) NULL,
	datet int NULL,
	note varchar(80) NULL,
	moneytypes varchar(50) NULL,
	rate varchar(20) NULL,
	sendcompany nvarchar(80) NULL,
	i_man decimal(18, 4) NULL,
	remark nvarchar(200) NULL,
	states nvarchar(50) NULL,
	sale_man nvarchar(50) NULL,
	sale_dept nvarchar(50) NULL,
	deptjb char(15) NULL,
	co_number char(30) NULL,
	total decimal,
	total_out_house decimal,
	to_gather_date date,
	gather_time datetime
)

CREATE TABLE m_document(
	id int IDENTITY(1,1) NOT NULL,
	l_menber char(20) NOT NULL,
	l_man char(10) NOT NULL,
	l_dept nvarchar(80) NULL,
	l_deptjb char(10) NULL,
	l_date datetime NULL,
	l_role nvarchar(90) NULL,
	l_dg_date nvarchar(90) NULL,
	l_zz_date nvarchar(90) NULL,
	l_tzsx nvarchar(90) NULL,
	l_ylxz nvarchar(90) NULL,
	l_tzbl nvarchar(90) NULL,
	l_tzje nvarchar(90) NULL,
	l_tzhxz nvarchar(90) NULL,
	l_jcyy ntext NULL,
	remarks ntext NULL,
	l_spqk nvarchar(70) NULL,
	l_spyj nvarchar(370) NULL,
	l_fqr nvarchar(25) NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL
)

CREATE TABLE shtsp(
	id int IDENTITY(1,1) NOT NULL,
	dept char(30) NULL,
	role char(15) NULL,
	price_min int NULL,
	price_max int NULL,
	ifsp char(10) NULL,
	dd_man char(15) NOT NULL,
	iffsp char(10) NULL,
	fsp_man char(20) NULL,
	firsp char(10) NULL,
	fir_man char(20) NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL
)

CREATE TABLE sam_sp(
	id int IDENTITY(1,1) NOT NULL,
	dept char(30) NULL,
	role char(15) NULL,
	price_min int NULL,
	price_max int NULL,
	dd_man char(15) NOT NULL,
	fif char(10) NOT NULL,
	fspman varchar(50) NOT NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL
)

CREATE TABLE dhsp(
	id int IDENTITY(1,1) NOT NULL,
	dept char(30) NULL,
	role char(15) NULL,
	dd_man char(15) NOT NULL,
	fif char(10) NOT NULL,
	fspman varchar(50) NOT NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL
)

CREATE TABLE getmail(
	id int IDENTITY(1,1) NOT NULL,
	mail_to nvarchar(100) NULL,
	mail_to2 nvarchar(100) NULL,
	mail_to3 nvarchar(100) NULL,
	mail_sub nvarchar(500) NULL,
	mail_nr ntext NULL,
	mail_man char(15) NULL,
	deptjb char(15) NULL,
	dept nvarchar(80) NULL,
	mail_datetime nvarchar(30) NULL,
	getman char(15) NULL,
	form_datetime char(30) NULL,
	states char(15) NULL,
	sid int NULL
)

CREATE TABLE m_commision(
	id int IDENTITY(1,1) NOT NULL,
	l_menber char(20) NOT NULL,
	l_man char(10) NOT NULL,
	l_dept nvarchar(80) NULL,
	l_deptjb char(10) NULL,
	l_date datetime NOT NULL,
	coname nvarchar(50) NULL,
	pi_number nvarchar(50) NULL,
	pro_model nvarchar(50) NULL,
	price char(30) NULL,
	p_num char(30) NULL,
	zprice char(30) NULL,
	yj char(30) NULL,
	coname2 nvarchar(50) NULL,
	pi_number2 nvarchar(50) NULL,
	pro_model2 nvarchar(50) NULL,
	price2 char(30) NULL,
	p_num2 char(30) NULL,
	zprice2 char(30) NULL,
	yj2 char(30) NULL,
	coname3 nvarchar(50) NULL,
	pi_number3 nvarchar(50) NULL,
	pro_model3 nvarchar(50) NULL,
	price3 char(30) NULL,
	p_num3 char(30) NULL,
	zprice3 char(30) NULL,
	yj3 char(30) NULL,
	l_jcyy ntext NULL,
	yj_man nvarchar(350) NULL,
	l_types nvarchar(50) NULL,
	l_bank nvarchar(150) NULL,
	l_sq_date nvarchar(50) NULL,
	l_sj_date nvarchar(50) NULL,
	remarks ntext NULL,
	l_spqk nvarchar(70) NULL,
	l_spyj nvarchar(370) NULL,
	l_fqr nvarchar(25) NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL
)

CREATE TABLE m_spbm(
	id int IDENTITY(1,1) NOT NULL,
	l_menber char(20) NOT NULL,
	l_man char(10) NOT NULL,
	l_dept nvarchar(80) NULL,
	l_deptjb char(10) NULL,
	l_date nvarchar(90) NULL,
	l_dg_date char(15) NULL,
	l_zz_date char(15) NULL,
	l_jcyy ntext NULL,
	l_pic nvarchar(150) NULL,
	remarks ntext NULL,
	l_spqk nvarchar(70) NULL,
	l_spyj nvarchar(370) NULL,
	l_fqr nvarchar(25) NULL,
	l_spman nvarchar(50) NULL,
	l_fif char(10) NULL,
	l_fspman char(15) NULL,
	l_firspif char(10) NULL,
	l_firspman char(15) NULL,
	in_no int NULL
)

CREATE TABLE th_table(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	man varchar(30) NOT NULL,
	sub nvarchar(60) NULL,
	coname varchar(60) NOT NULL,
	senddate nvarchar(20) NULL,
	money char(10) NOT NULL,
	habitus varchar(10) NOT NULL,
	datetime datetime NOT NULL,
	remarks ntext NULL,
	state varchar(10) NOT NULL,
	spman varchar(50) NULL,
	spdate nvarchar(50) NULL,
	spyj nvarchar(300) NULL,
	fif char(10) NULL,
	cwman char(15) NULL,
	cwdate nvarchar(50) NULL,
	cwyj varchar(300) NULL,
	firspif char(10) NULL,
	firspman char(15) NULL,
	fspyj nvarchar(300) NULL,
	dept char(30) NULL,
	deptjb char(10) NULL,
	in_no int NULL,
	w_remark nvarchar(350) NULL,
	return_way varchar(50) NULL,
	payway varchar(50) NULL
)

CREATE TABLE hh_goods(
	id int IDENTITY(1,1) NOT NULL,
	l_menber nvarchar(50) NULL,
	l_man char(10) NULL,
	l_dept nvarchar(50) NULL,
	l_deptjb char(15) NULL,
	l_date char(15) NULL,
	hh_from nvarchar(90) NULL,
	hh_to nvarchar(90) NULL,
	hh_from_tel nvarchar(50) NULL,
	hh_from_fax nvarchar(50) NULL,
	hh_to_add nvarchar(90) NULL,
	hh_from_add nvarchar(90) NULL,
	hh_to_tel nvarchar(50) NULL,
	hh_to_fax nvarchar(50) NULL,
	hh_from_zip char(10) NULL,
	hh_from_contact char(30) NULL,
	hh_to_zip char(10) NULL,
	hh_pi nvarchar(50) NULL,
	pro_model nvarchar(50) NULL,
	pro_number char(30) NULL,
	hh_yy nvarchar(90) NULL,
	hh_hj nvarchar(50) NULL,
	hh_date char(15) NULL,
	pro_model2 nvarchar(50) NULL,
	pro_number2 char(30) NULL,
	hh_yy2 nvarchar(90) NULL,
	hh_hj2 nvarchar(50) NULL,
	hh_date2 char(15) NULL,
	pro_model3 nvarchar(50) NULL,
	pro_number3 char(30) NULL,
	hh_yy3 nvarchar(90) NULL,
	hh_hj3 nvarchar(50) NULL,
	hh_date3 char(15) NULL,
	pro_model4 nvarchar(50) NULL,
	pro_number4 char(30) NULL,
	hh_yy4 nvarchar(90) NULL,
	hh_hj4 nvarchar(50) NULL,
	hh_date4 char(15) NULL,
	pro_model5 nvarchar(50) NULL,
	pro_number5 char(30) NULL,
	hh_yy5 nvarchar(90) NULL,
	hh_hj5 nvarchar(50) NULL,
	hh_date5 char(15) NULL,
	hh_sj_date nvarchar(50) NULL,
	hh_xh_date nvarchar(50) NULL,
	l_spman char(10) NULL,
	hh_jy_date nvarchar(90) NULL,
	hh_xxms nvarchar(550) NULL,
	hh_jy_jl nvarchar(350) NULL,
	hh_js_yj nvarchar(350) NULL,
	l_fspman char(10) NULL,
	hh_dept_yj nvarchar(350) NULL,
	l_firspman char(10) NULL,
	hh_zg_yj nvarchar(350) NULL,
	hh_if_sd char(10) NULL,
	hh_m_man char(10) NULL,
	hh_m_yj nvarchar(150) NULL,
	hh_po_man char(10) NULL,
	hh_po_yj nvarchar(150) NULL,
	remark text NULL,
	l_spqk char(10) NULL,
	in_no int NULL
)

CREATE TABLE appeal(
	aid int IDENTITY(1,1) NOT NULL,
	numeration varchar(50) NOT NULL,
	appealfl varchar(50) NULL,
	appealdj varchar(50) NULL,
	state varchar(50) NULL,
	creatdt varchar(50) NULL,
	enddt varchar(50) NULL,
	receipt varchar(50) NULL,
	groupnumber varchar(50) NULL,
	ordernumber varchar(50) NULL,
	contract varchar(50) NULL,
	epro varchar(150) NULL,
	cpro varchar(150) NULL,
	number varchar(50) NULL,
	unit varchar(50) NULL,
	standard varchar(260) NULL,
	transport varchar(260) NULL,
	supplier varchar(150) NULL,
	sdate varchar(50) NULL,
	customer varchar(150) NULL,
	cdate varchar(50) NULL,
	appeallr text NULL,
	checknr text NULL,
	checkman varchar(50) NULL,
	checkdate varchar(50) NULL,
	clfa text NULL,
	clfaman varchar(50) NULL,
	clfadate varchar(50) NULL,
	feedback text NULL,
	feedbackman varchar(50) NULL,
	feedbackdate varchar(50) NULL,
	remarks text NULL,
	spmanger char(10) NULL,
	spdate char(10) NULL,
	spyj nvarchar(300) NULL,
	cml char(10) NULL,
	cfk nvarchar(300) NULL,
	in_no int NULL
)

CREATE TABLE customer_gj(
	id int IDENTITY(1,1) NOT NULL,
	c_date datetime NULL,
	c_time char(15) NULL,
	man char(10) NULL,
	dept nvarchar(50) NULL,
	deptjb char(10) NULL,
	co_number char(30) NULL,
	c_name nvarchar(100) NULL,
	actypes nvarchar(50) NULL,
	c_nr ntext NULL,
	remark ntext NULL,
	iftx char(10) NULL,
	txtime datetime NULL,
	coid char(10) NULL
)

CREATE TABLE outhouse(
	id int IDENTITY(1,1) NOT NULL,
	pro_fynum varchar(50) NOT NULL,
	pro_coname nvarchar(120) NULL,
	pro_model nvarchar(80) NULL,
	pro_name nvarchar(80) NULL,
	pro_num int NULL,
	pro_unit char(10) NULL,
	pro_supplier nvarchar(80) NULL,
	pro_datetime char(15) NULL,
	pro_number varchar(50) NULL,
	slinkman nvarchar(90) NULL,
	slinktel char(30) NULL,
	states char(30) NULL,
	ddid char(10) NULL,
	remark varchar(300) NULL,
	wid char(10) NULL,
	pro_coname_num char(30) NULL,
	pro_sales_price decimal(18, 6) NULL,
	pro_price_hb char(15) NULL,
	pro_rate_types char(30) NULL,
	pro_rate varchar(50) NULL,
	pro_out_num char(15) NOT NULL,
	in_no int NULL,
	salejg decimal(18, 4) NULL
)

CREATE TABLE transportation(
	id int IDENTITY(1,1) NOT NULL,
	ddid nvarchar(50) NOT NULL,
	fyid nvarchar(50) NOT NULL,
	invoice varchar(50) NOT NULL,
	subscribe varchar(50) NOT NULL,
	coname varchar(100) NOT NULL,
	trans_com varchar(100) NULL,
	aimport varchar(350) NULL,
	fy_num nvarchar(50) NULL,
	fy_yf decimal(18, 2) NULL,
	fy_bf decimal(18, 2) NULL,
	fy_js nvarchar(50) NULL,
	fy_sz nvarchar(50) NULL,
	transportation varchar(90) NULL,
	mode nvarchar(50) NULL,
	datet int NULL,
	mbdate varchar(50) NULL,
	sjdate varchar(50) NULL,
	linkman varchar(50) NULL,
	linktel varchar(50) NULL,
	sendcompany nvarchar(100) NULL,
	slinkman nvarchar(50) NULL,
	slinktel nvarchar(50) NULL,
	sate varchar(50) NULL,
	sale_man char(15) NULL,
	sale_dept char(30) NULL,
	deptjb char(10) NULL,
	remark nvarchar(350) NULL,
	co_number char(30) NULL,
	tr_types char(15) NULL,
	fy_date char(15) NULL,
	yf_types char(50) NULL,
	yf_money decimal(18, 2) NULL,
	in_no int NULL,
	tr_print char(10) NULL
)

CREATE TABLE o_pic(
	id int IDENTITY(1,1) NOT NULL,
	oid char(10) NULL,
	pic_sm nvarchar(100) NULL,
	pic_path nvarchar(50) NULL
)

CREATE TABLE pro_sup(
	id int IDENTITY(1,1) NOT NULL,
	pro_id nvarchar(50) NOT NULL,
	pro_sup_id char(30) NOT NULL,
	pro_sup_name nvarchar(80) NULL,
	pro_sup_price decimal(18, 2) NULL,
	pro_sup_hb char(10) NULL,
	pro_sup_rate char(20) NULL,
	pro_sup_date nvarchar(50) NULL,
	pro_sup_remark nvarchar(100) NULL
)

CREATE TABLE role_right(
	id int IDENTITY(1,1) NOT NULL,
	role_id int NULL,
	role_name varchar(50) NULL,
	right_name varchar(50) NULL,
	right_add int NULL,
	right_update int NULL,
	right_delete int NULL,
	right_enable int NULL,
	pro_addr varchar(15) NULL
)

CREATE TABLE quoteproduct(
	id int IDENTITY(1,1) NOT NULL,
	quoteid varchar(50) NOT NULL,
	product varchar(150) NULL,
	cpro varchar(70) NULL,
	cpro2 nvarchar(70) NULL,
	pro_gg nvarchar(50) NULL,
	quantity int NULL,
	unit varchar(50) NULL,
	price decimal(18, 4) NULL,
	pricehb varchar(50) NULL,
	selljg decimal(18, 4) NULL,
	money char(10) NULL,
	supplier varchar(150) NULL,
	wid nvarchar(50) NULL,
	rate_types char(10) NULL,
	rate int NULL,
	remark varchar(300) NULL,
	moq varchar(50) NULL,
	mpq varchar(50) NULL
)

CREATE TABLE warehouse_in_out_log(
	id varchar(50) NOT NULL,
	number varchar(50) NOT NULL,
	orgin_num int NOT NULL,
	change_num int NOT NULL,
	final_num int NOT NULL,
	operateTime datetime NOT NULL,
	operater varchar(50) NOT NULL,
	wid int NOT NULL,
	rk_id int NULL,
	memo varchar(50) NOT NULL
)

CREATE TABLE profll(
	id int IDENTITY(1,1) NOT NULL,
	oid char(10) NULL,
	seccode nvarchar(10) NULL,
	cpro nvarchar(80) NULL,
	epro nvarchar(80) NULL,
	remark nvarchar(500) NULL,
	tnumber char(10) NOT NULL
)

CREATE TABLE secprofl(
	id int IDENTITY(1,1) NOT NULL,
	firstkind nvarchar(10) NULL,
	proflname nvarchar(45) NULL,
	eprofl nvarchar(45) NULL,
	price_gk decimal(18, 2) NULL,
	price_jysj decimal(18, 2) NULL,
	price_min decimal(18, 2) NULL,
	price_dljg decimal(18, 2) NULL,
	price_wf decimal(18, 2) NULL,
	remark nvarchar(150) NULL,
	snumber char(8) NOT NULL
)

CREATE TABLE qlinkman(
	nameid int IDENTITY(1,1) NOT NULL,
	name varchar(50) NOT NULL,
	job varchar(50) NULL,
	mr varchar(50) NULL,
	email varchar(50) NULL,
	tel varchar(50) NULL,
	department varchar(50) NULL,
	bornde varchar(50) NULL,
	school varchar(150) NULL,
	degree varchar(50) NULL,
	born varchar(50) NULL,
	co_number char(30) NULL,
	coname varchar(150) NULL,
	coaddr varchar(150) NULL,
	cotel varchar(50) NULL,
	cofax varchar(50) NULL,
	prorole varchar(50) NULL,
	evaluate varchar(100) NULL,
	artifice varchar(100) NULL,
	waptel varchar(50) NULL,
	myaddr nvarchar(100) NULL,
	interest varchar(300) NULL,
	username varchar(50) NULL,
	rg_date datetime NULL,
	dept nvarchar(50) NULL,
	deptjb char(10) NULL,
	share varchar(50) NULL,
	modman char(15) NULL,
	mod_date datetime NULL,
	beizhu varchar(300) NULL,
	qq varchar(50) NULL,
	msn ntext NULL,
	skype varchar(50) NULL
)

CREATE TABLE supplier_attachment(
	id int IDENTITY(1,1) NOT NULL,
	supplierid int NULL,
	filename varchar(200) NULL,
	filepath varchar(320) NULL,
	remark ntext NULL
)

CREATE TABLE dd_del_log(
	id int IDENTITY(1,1) NOT NULL,
	ddid varchar(50) NULL,
	operator varchar(50) NULL,
	operateTime datetime NULL,
	remark ntext NULL
)

CREATE TABLE thsp(
	id int IDENTITY(1,1) NOT NULL,
	dept char(30) NULL,
	role char(15) NULL,
	dd_man char(15) NOT NULL,
	fif char(10) NOT NULL,
	fspman varchar(50) NOT NULL,
	firspif char(10) NULL,
	firspman char(20) NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL
)

CREATE TABLE th_pro(
	id int IDENTITY(1,1) NOT NULL,
	ddid varchar(50) NOT NULL,
	epro varchar(150) NOT NULL,
	num int NOT NULL,
	fypronum varchar(50) NULL,
	unit varchar(50) NULL,
	cpro varchar(150) NULL,
	rale_types varchar(50) NULL,
	rale decimal(10, 2) NULL,
	supplier varchar(150) NULL,
	pricehb nvarchar(30) NOT NULL,
	salejg decimal(18, 2) NOT NULL,
	selljg decimal(18, 2) NULL,
	money varchar(50) NULL,
	fyproall char(15) NULL,
	wid char(10) NULL,
	s_num int NULL,
	s_c_num int NULL,
	s_tr_date nvarchar(50) NULL,
	fy_states char(150) NULL,
	remark nvarchar(500) NULL,
	ddpro_id int NULL,
	subscribe_id int NULL
)

CREATE TABLE th_info(
	id int IDENTITY(1,1) NOT NULL,
	operateTime datetime NULL,
	operateMan varchar(100) NULL,
	pro_model varchar(100) NULL,
	remark ntext NULL
)

CREATE TABLE gathering_refund(
	id int IDENTITY(1,1) NOT NULL,
	fyid char(50) NULL,
	invoice varchar(50) NOT NULL,
	orderform varchar(50) NOT NULL,
	imoney decimal(18, 4) NULL,
	ymoney decimal(18, 4) NULL,
	smoney decimal(18, 4) NULL,
	coname varchar(80) NULL,
	bank decimal(18, 4) NULL,
	bankaccounts varchar(80) NULL,
	yjskdate varchar(30) NULL,
	sjdate varchar(30) NULL,
	sjskdate datetime NULL,
	skdate char(15) NULL,
	mode varchar(80) NULL,
	datet int NULL,
	note varchar(80) NULL,
	moneytypes varchar(50) NULL,
	rate varchar(20) NULL,
	sendcompany nvarchar(80) NULL,
	i_man decimal(18, 4) NULL,
	remark nvarchar(200) NULL,
	states nvarchar(50) NULL,
	sale_man nvarchar(50) NULL,
	sale_dept nvarchar(50) NULL,
	deptjb char(15) NULL,
	co_number char(30) NULL
)

CREATE TABLE linkman(
	nameid int IDENTITY(1,1) NOT NULL,
	name varchar(50) NOT NULL,
	job varchar(50) NULL,
	mr varchar(50) NULL,
	email varchar(50) NULL,
	tel varchar(50) NULL,
	department varchar(50) NULL,
	bornde varchar(50) NULL,
	school varchar(150) NULL,
	degree varchar(50) NULL,
	born varchar(50) NULL,
	co_number char(30) NULL,
	coname varchar(150) NULL,
	coaddr varchar(150) NULL,
	cotel varchar(50) NULL,
	cofax varchar(50) NULL,
	prorole varchar(50) NULL,
	evaluate varchar(200) NULL,
	artifice varchar(200) NULL,
	post varchar(50) NULL,
	city varchar(50) NULL,
	country varchar(80) NULL,
	province varchar(50) NULL,
	waptel varchar(50) NULL,
	interest varchar(300) NULL,
	username varchar(50) NULL,
	rg_date datetime NULL,
	dept char(30) NULL,
	deptjb char(30) NULL,
	modman char(15) NULL,
	mod_date datetime NULL,
	share varchar(50) NULL,
	beizhu varchar(300) NULL,
	qq varchar(50) NULL,
	msn varchar(50) NULL,
	skype varchar(50) NULL
)

CREATE TABLE pf_client(
	id int IDENTITY(1,1) NOT NULL,
	co_number varchar(30) NULL,
	username varchar(30) NULL,
	rfq float NULL,
	gmjl float NULL,
	fk float NULL,
	th float NULL,
	remark ntext NULL,
	pf_datetime datetime NULL
)

CREATE TABLE thsp_supplier(
	id int IDENTITY(1,1) NOT NULL,
	dept char(30) NULL,
	role char(15) NULL,
	dd_man char(15) NOT NULL,
	fif char(10) NOT NULL,
	fspman varchar(50) NOT NULL,
	firspif char(10) NULL,
	firspman char(20) NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL,
	price_min decimal(18, 0) NULL,
	price_max decimal(18, 0) NULL
)

CREATE TABLE th_pro_supplier(
	id int IDENTITY(1,1) NOT NULL,
	ddid int NOT NULL,
	epro varchar(150) NOT NULL,
	num int NOT NULL,
	fypronum char(10) NULL,
	unit varchar(50) NULL,
	cpro varchar(150) NULL,
	rale_types varchar(50) NULL,
	rale decimal(10, 2) NULL,
	supplier varchar(150) NULL,
	pricehb nvarchar(30) NOT NULL,
	salejg decimal(18, 4) NOT NULL,
	selljg decimal(18, 4) NULL,
	money varchar(50) NULL,
	fyproall char(15) NULL,
	wid varchar(50) NULL,
	s_num int NULL,
	s_c_num int NULL,
	s_tr_date nvarchar(50) NULL,
	fy_states char(150) NULL,
	th_number varchar(50) NULL,
	cg_number varchar(50) NULL,
	remark varchar(350) NULL,
	csdhs nvarchar(max) NULL,
	th_num int NULL
)

CREATE TABLE km_ty(
	id int IDENTITY(1,1) NOT NULL,
	km_name nvarchar(100) NOT NULL,
	remark nvarchar(200) NULL,
	km_date datetime NULL
)

CREATE TABLE rulestable(
	id int IDENTITY(1,1) NOT NULL,
	titel nvarchar(150) NULL,
	content ntext NULL,
	username nvarchar(50) NULL,
	fvdate nvarchar(50) NULL,
	dept nvarchar(50) NULL,
	deptjb nvarchar(50) NULL
)


CREATE TABLE warehouse_right(
	id int IDENTITY(1,1) NOT NULL,
	warehouse_id int,
	restrain_id int,
	restrain_warehouse_right int
)

CREATE TABLE pd(
	pro_model varchar(500) NULL,
	a int NULL,
	b int NULL,
	c int NULL,
	d int NULL,
	e int NULL,
	f int NULL,
	g int NULL,
	h int NULL,
	i int NULL,
	pro_addr varchar(50) NULL,
	status int NULL
) 

CREATE TABLE yptransportation(
	id int IDENTITY(1,1) NOT NULL,
	ddid nvarchar(50) NOT NULL,
	fyid nvarchar(50) NOT NULL,
	invoice varchar(50) NOT NULL,
	subscribe varchar(50) NOT NULL,
	coname varchar(100) NOT NULL,
	trans_com varchar(100) NULL,
	aimport varchar(100) NULL,
	fy_num nvarchar(50) NULL,
	fy_yf decimal(18, 2) NULL,
	fy_bf decimal(18, 2) NULL,
	fy_js nvarchar(50) NULL,
	fy_sz nvarchar(50) NULL,
	transportation varchar(90) NULL,
	mode nvarchar(50) NULL,
	datet int NULL,
	mbdate varchar(50) NULL,
	sjdate varchar(50) NULL,
	linkman varchar(50) NULL,
	linktel varchar(50) NULL,
	sendcompany nvarchar(100) NULL,
	slinkman nvarchar(50) NULL,
	slinktel nvarchar(50) NULL,
	sate varchar(50) NULL,
	sale_man char(15) NULL,
	sale_dept char(30) NULL,
	deptjb char(10) NULL,
	remark nvarchar(350) NULL,
	co_number char(30) NULL,
	tr_types char(15) NULL,
	fy_date char(15) NULL,
	yf_types char(15) NULL,
	yf_money decimal(18, 2) NULL,
	in_no int NULL,
	tr_print char(10) NULL
)

CREATE TABLE hdcompany(
	id int IDENTITY(1,1) NOT NULL,
	companyname varchar(150) NULL,
	companytel varchar(50) NULL,
	companyaddr varchar(150) NULL,
	companyfax varchar(50) NULL,
	companynet varchar(50) NULL,
	companyemail varchar(50) NULL,
	linkman varchar(50) NULL,
	linkmantel varchar(50) NULL,
	remark ntext NULL
)

CREATE TABLE hdcompany_attachment(
	id int IDENTITY(1,1) NOT NULL,
	hdcompanyid int NULL,
	filename varchar(200) NULL,
	filepath varchar(320) NULL,
	remark ntext NULL
)

CREATE TABLE supplier_attachment(
	id int IDENTITY(1,1) NOT NULL,
	supplierid int NULL,
	filename varchar(200) NULL,
	filepath varchar(320) NULL,
	remark ntext NULL
)

CREATE TABLE payment_customer(
	id int IDENTITY(1,1) NOT NULL,
	co_number nvarchar(50) NULL,
	coname nvarchar(100) NULL,
	coaddr nvarchar(100) NULL,
	cofrdb char(15) NULL,
	cotel nvarchar(50) NULL,
	cofax nvarchar(50) NULL,
	bank nvarchar(100) NULL,
	payment_je decimal(18, 2) NULL,
	payment_sje decimal(18, 2) NULL,
	money char(10) NULL,
	salesman char(15) NULL,
	remark ntext NULL,
	payment_date datetime NULL,
	dept nvarchar(100) NULL,
	deptjb char(15) NULL
)

CREATE TABLE gathering_customer(
	id int IDENTITY(1,1) NOT NULL,
	coname nvarchar(100) NULL,
	coaddr nvarchar(100) NULL,
	cofrdb nvarchar(50) NULL,
	cotel nvarchar(50) NULL,
	cofax nvarchar(50) NULL,
	bank nvarchar(100) NULL,
	payment_je decimal(18, 4) NULL,
	payment_sje decimal(18, 4) NULL,
	money char(10) NULL,
	remark ntext NULL,
	payment_date datetime NULL,
	co_number nvarchar(50) NULL,
	dept nvarchar(90) NULL,
	deptjb char(20) NULL,
	pname char(15) NULL
)

CREATE TABLE bank(
	id int IDENTITY(1,1) NOT NULL,
	com_bank varchar(90) NOT NULL,
	bank varchar(90) NOT NULL,
	bank_num varchar(50) NOT NULL,
	bank_je decimal(18, 2) NULL,
	bank_hb char(10) NULL,
	remark nvarchar(300) NULL,
	bank_date datetime NOT NULL,
	dept nvarchar(90) NULL,
	deptjb char(10) NULL,
	hiddens varchar(10) NULL
)

CREATE TABLE opportunity(
	sellid int IDENTITY(1,1) NOT NULL,
	sell varchar(80) NOT NULL,
	description ntext NULL,
	xplan varchar(80) NULL,
	origin varchar(80) NULL,
	salem varchar(50) NULL,
	saledt varchar(50) NULL,
	coname varchar(150) NULL,
	coaddr varchar(150) NULL,
	copost varchar(50) NULL,
	city varchar(50) NULL,
	cotel varchar(50) NULL,
	cofax varchar(50) NULL,
	forecast numeric(19, 2) NULL,
	creatdt varchar(50) NULL,
	enddt varchar(50) NULL,
	succeed varchar(50) NULL,
	state varchar(50) NULL,
	stop varchar(150) NULL,
	username varchar(50) NULL,
	usertime varchar(50) NULL,
	dept nvarchar(50) NULL,
	deptjb char(15) NULL
)

CREATE TABLE activity(
	id int IDENTITY(1,1) NOT NULL,
	actypes varchar(50) NULL,
	coname varchar(150) NULL,
	coaddr nvarchar(100) NULL,
	coman char(30) NULL,
	cotel char(60) NULL,
	cofax char(30) NULL,
	conet nvarchar(80) NULL,
	coemail nvarchar(80) NULL,
	name varchar(50) NULL,
	clewtime varchar(50) NULL,
	ytime varchar(50) NULL,
	iftx char(10) NULL,
	txtime varchar(50) NULL,
	state varchar(50) NULL,
	pri char(10) NULL,
	descripta ntext NULL,
	remark ntext NULL,
	deptjb char(30) NULL
)

CREATE TABLE Inquiry(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	quotedatetime varchar(50) NULL,
	co_number char(30) NULL,
	coname varchar(150) NULL,
	cotel varchar(50) NULL,
	coaddr varchar(150) NULL,
	cofax varchar(50) NULL,
	linkman varchar(50) NULL,
	linktel varchar(50) NULL,
	linkwap varchar(50) NULL,
	linkemail varchar(50) NULL,
	man varchar(50) NULL,
	dept nvarchar(50) NULL,
	deptjb nvarchar(50) NULL,
	content ntext NULL,
	states nvarchar(50) NULL,
	in_no int NULL,
	cgman char(15) NULL,
	xj_date nvarchar(50) NULL,
	country nvarchar(50) NULL,
	province nvarchar(50) NULL,
	city nvarchar(50) NULL,
	hf_date nvarchar(50) NULL,
	copost char(10) NULL,
	c_types char(30) NULL,
	in_man nvarchar(390) NULL,
	in_f_datetime nvarchar(50) NULL,
	courier nvarchar(50) NULL,
	acct nvarchar(50) NULL,
	terms nvarchar(50) NULL
)

CREATE TABLE menber(
	id int IDENTITY(1,1) NOT NULL,
	pic_path nvarchar(50) NULL,
	name nvarchar(50) NULL,
	dept nvarchar(90) NULL,
	deptjb char(10) NULL,
	business nvarchar(50) NULL,
	jiondt nvarchar(50) NULL,
	borndt nvarchar(50) NULL,
	sex char(10) NULL,
	man_zzmm nvarchar(50) NULL,
	nation nvarchar(50) NULL,
	man_h nvarchar(50) NULL,
	idcard nvarchar(50) NULL,
	man_tc nvarchar(50) NULL,
	nativeplace nvarchar(90) NULL,
	xzaddr nvarchar(90) NULL,
	born_addr nvarchar(90) NULL,
	hunif char(10) NULL,
	man_tel nvarchar(50) NULL,
	man_school nvarchar(100) NULL,
	school_date nvarchar(50) NULL,
	school_zy nvarchar(50) NULL,
	school_year nvarchar(50) NULL,
	school_age nvarchar(50) NULL,
	degree nvarchar(50) NULL,
	dimissiom_date nvarchar(50) NULL,
	man_english nvarchar(90) NULL,
	man_computator nvarchar(90) NULL,
	man_jj_lxr char(50) NULL,
	man_jj_tel nvarchar(50) NULL,
	man_jj_addr nvarchar(90) NULL,
	family_name1 nvarchar(50) NULL,
	family_gx1 nvarchar(50) NULL,
	family_work_name1 nvarchar(150) NULL,
	family_zw1 nvarchar(50) NULL,
	family_tel1 nvarchar(50) NULL,
	family_name2 nvarchar(50) NULL,
	family_gx2 nvarchar(50) NULL,
	family_work_name2 nvarchar(150) NULL,
	family_zw2 nvarchar(50) NULL,
	family_tel2 nvarchar(50) NULL,
	family_name3 nvarchar(50) NULL,
	family_gx3 nvarchar(50) NULL,
	family_work_name3 nvarchar(150) NULL,
	family_zw3 nvarchar(50) NULL,
	family_tel3 nvarchar(50) NULL,
	work_sdate char(15) NULL,
	work_edate char(15) NULL,
	work_company nvarchar(150) NULL,
	work_zw char(30) NULL,
	work_tel nvarchar(50) NULL,
	work_sdate1 char(15) NULL,
	work_edate1 char(15) NULL,
	work_company1 nvarchar(150) NULL,
	work_zw1 char(30) NULL,
	work_tel1 nvarchar(50) NULL,
	work_sdate2 char(15) NULL,
	work_edate2 char(15) NULL,
	work_company2 nvarchar(150) NULL,
	work_zw2 char(30) NULL,
	work_tel2 nvarchar(50) NULL,
	man_zz nvarchar(200) NULL,
	man_cb nvarchar(200) NULL,
	man_ht nvarchar(200) NULL,
	remark ntext NULL
)

CREATE TABLE programer(
	id int IDENTITY(1,1) NOT NULL,
	xmnumber char(30) NULL,
	starttime nvarchar(50) NULL,
	application varchar(50) NULL,
	spman varchar(50) NULL,
	programername varchar(60) NULL,
	prog_je char(50) NULL,
	xm_types nvarchar(50) NULL,
	prog_coname nvarchar(90) NULL,
	prog_coman char(30) NULL,
	prog_cotel nvarchar(50) NULL,
	prog_nr ntext NULL,
	situation ntext NULL,
	progress ntext NULL,
	prog_jg varchar(300) NULL,
	remark varchar(500) NULL,
	states nvarchar(50) NULL,
	spdate nvarchar(50) NULL,
	spyj nvarchar(500) NULL,
	dept char(35) NULL,
	deptjb char(15) NULL,
	in_no int NULL,
	m_ps nvarchar(500) NULL,
	last_update_time datetime
)

CREATE TABLE man_kh(
	id int IDENTITY(1,1) NOT NULL,
	menberid char(10) NULL,
	name nvarchar(50) NULL,
	man_kdate nvarchar(50) NULL,
	man_klx nvarchar(150) NULL,
	man_kh ntext NULL,
	remark ntext NULL
)

CREATE TABLE man_jf(
	id int IDENTITY(1,1) NOT NULL,
	menberid char(10) NULL,
	name nvarchar(50) NULL,
	man_kdate nvarchar(50) NULL,
	man_klx nvarchar(150) NULL,
	man_kh ntext NULL,
	remark ntext NULL
)

CREATE TABLE man_dd(
	id int IDENTITY(1,1) NOT NULL,
	menberid char(10) NULL,
	name nvarchar(50) NULL,
	man_kdate nvarchar(50) NULL,
	man_klx nvarchar(150) NULL,
	man_kh ntext NULL,
	remark ntext NULL
)

CREATE TABLE man_xz(
	id int IDENTITY(1,1) NOT NULL,
	menberid char(10) NULL,
	name nvarchar(50) NULL,
	man_kdate nvarchar(50) NULL,
	man_klx nvarchar(150) NULL,
	man_kh ntext NULL,
	remark ntext NULL
)

CREATE TABLE km_f(
	id int IDENTITY(1,1) NOT NULL,
	coun_number char(20) NULL,
	coun_name nvarchar(100) NULL,
	coun_ename nvarchar(100) NULL
)


CREATE TABLE wage_menber(
	id int IDENTITY(1,1) NOT NULL,
	wage_name nvarchar(50) NOT NULL,
	wage_year char(10) NULL,
	wage_month char(10) NULL,
	wage_date datetime NOT NULL,
	wage_rgman nvarchar(50) NULL,
	wage_m_dates decimal(18, 1) NULL,
	wage_date_price decimal(18, 2) NULL,
	wage_month_dates decimal(18, 2) NULL,
	wage_awork_price decimal(18, 0) NULL,
	wage_awork_h decimal(18, 2) NULL,
	wage_zf_price decimal(18, 0) NULL,
	wage_jt_price decimal(18, 0) NULL,
	wage_wc_price decimal(18, 0) NULL,
	wage_sb_price decimal(18, 0) NULL,
	wage_zdy_sub nvarchar(50) NULL,
	wage_zdy_price decimal(18, 0) NULL,
	wage_zdy_qy char(10) NULL,
	wage_zdy_zj char(10) NULL,
	wage_zdy_sub2 nvarchar(50) NULL,
	wage_zdy_price2 decimal(18, 0) NULL,
	wage_zdy_qy2 char(10) NULL,
	wage_zdy_zj2 char(10) NULL,
	wage_zdy_sub3 nvarchar(50) NULL,
	wage_zdy_price3 decimal(18, 0) NULL,
	wage_zdy_qy3 char(10) NULL,
	wage_zdy_zj3 char(10) NULL,
	wage_zdy_sub4 nvarchar(50) NULL,
	wage_zdy_price4 decimal(18, 0) NULL,
	wage_zdy_qy4 char(10) NULL,
	wage_zdy_zj4 char(10) NULL,
	wage_zdy_sub5 nvarchar(50) NULL,
	wage_zdy_price5 decimal(18, 0) NULL,
	wage_zdy_qy5 char(10) NULL,
	wage_zdy_zj5 char(10) NULL,
	remark ntext NULL,
	dept nvarchar(50) NULL,
	deptjb char(10) NULL
)

CREATE TABLE sales_bank(
	id int IDENTITY(1,1) NOT NULL,
	bname varchar(50) NULL,
	bn nvarchar(200) NULL,
	baddress varchar(50) NULL,
	ba nvarchar(200) NULL,
	scode varchar(50) NULL,
	sc nvarchar(200) NULL,
	bename varchar(50) NULL,
	ben nvarchar(200) NULL,
	ano varchar(50) NULL,
	an nvarchar(200) NULL
)

CREATE TABLE print_log(
	id int IDENTITY(1,1) NOT NULL,
	operator varchar(100) NULL,
	number varchar(50) NULL,
	created_time datetime NULL,
	type varchar(50) NULL
)

CREATE TABLE Inquiry(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	quotedatetime varchar(50) NULL,
	co_number char(30) NULL,
	coname varchar(150) NULL,
	cotel varchar(50) NULL,
	coaddr varchar(150) NULL,
	cofax varchar(50) NULL,
	linkman varchar(50) NULL,
	linktel varchar(50) NULL,
	linkwap varchar(50) NULL,
	linkemail varchar(50) NULL,
	man varchar(50) NULL,
	dept nvarchar(50) NULL,
	deptjb nvarchar(50) NULL,
	content ntext NULL,
	states nvarchar(50) NULL,
	in_no int NULL,
	cgman char(15) NULL,
	xj_date nvarchar(50) NULL,
	country nvarchar(50) NULL,
	province nvarchar(50) NULL,
	city nvarchar(50) NULL,
	hf_date nvarchar(50) NULL,
	copost char(10) NULL,
	c_types char(30) NULL,
	in_man nvarchar(390) NULL,
	in_f_datetime nvarchar(50) NULL,
	courier nvarchar(50) NULL,
	acct nvarchar(50) NULL,
	terms nvarchar(50) NULL
)

CREATE TABLE Inquiry_product(
	id int IDENTITY(1,1) NOT NULL,
	quoteid varchar(50) NOT NULL,
	supplier nvarchar(90) NULL,
	pro_sup_no nvarchar(200) NULL,
	pro_p_year nvarchar(50) NULL,
	pro_pro_no nvarchar(50) NULL,
	product varchar(500) NULL,
	cpro varchar(80) NULL,
	cpro2 nvarchar(80) NULL,
	quantity int NULL,
	punit varchar(50) NULL,
	price decimal(18, 4) NULL,
	price_hb char(15) NULL,
	pro_tr nvarchar(50) NULL,
	pro_report nvarchar(200) NULL,
	pro_remark varchar(150) NULL,
	pro_states char(15) NULL,
	wid char(10) NULL,
	xh int NULL,
	p_product nvarchar(500) NULL,
	p_pro_p_year nvarchar(50) NULL,
	p_quantity int NULL,
	p_price decimal(18, 4) NULL,
	p_supplier nvarchar(120) NULL,
	p_pro_tr nvarchar(50) NULL,
	q_price decimal(18, 2) NULL,
	p_hb char(10) NULL
)

CREATE TABLE procure_xj(
	id int IDENTITY(1,1) NOT NULL,
	number varchar(50) NOT NULL,
	man varchar(30) NULL,
	linkman nvarchar(60) NULL,
	co_number char(30) NULL,
	coname varchar(60) NULL,
	senddate varchar(90) NULL,
	sup_tel nvarchar(90) NULL,
	sup_fax nvarchar(90) NULL,
	datetime varchar(60) NULL,
	money char(15) NULL,
	tbyq nvarchar(200) NULL,
	remarks ntext NULL,
	state varchar(50) NULL,
	sp_man char(15) NULL,
	spyj nvarchar(200) NULL,
	in_number nvarchar(50) NULL,
	in_no int NULL
)

CREATE TABLE inquirys(
	ctype char(30) NULL,
	orders char(10) NULL
)

CREATE TABLE messageuser(
	id varchar(50) NOT NULL,
	username varchar(50) NULL,
	userpassword varchar(50) NULL
)

CREATE TABLE serverquest(
	id int IDENTITY(1,1) NOT NULL,
	record varchar(50) NULL,
	fwlx varchar(50) NULL,
	name varchar(50) NULL,
	tel varchar(50) NULL,
	coname varchar(150) NULL,
	import varchar(50) NULL,
	mqwc varchar(50) NULL,
	state varchar(50) NULL,
	descripts text NULL,
	starttime varchar(50) NULL,
	endtime varchar(50) NULL,
	deptjb varchar(50) NULL
)

CREATE TABLE total_pro(
	id int IDENTITY(1,1) NOT NULL,
	pro_id nvarchar(50) NOT NULL,
	pro_model char(80) NOT NULL,
	pro_name nvarchar(80) NULL,
	pro_num int NULL,
	pro_unit char(10) NULL,
	pro_date nvarchar(50) NULL,
	pro_remark nvarchar(100) NULL,
	wid char(10) NULL,
	sid char(10) NULL
)

CREATE TABLE checkwork_time(
	id int IDENTITY(1,1) NOT NULL,
	am_startchs char(10) NOT NULL,
	am_start char(10) NOT NULL,
	am_startche char(10) NOT NULL,
	am_startla int NOT NULL,
	if_am_start int NOT NULL,
	am_endchs char(10) NOT NULL,
	am_end char(10) NOT NULL,
	am_endche char(10) NOT NULL,
	am_endla int NOT NULL,
	if_am_end int NOT NULL,
	pm_startchs char(10) NOT NULL,
	pm_start char(10) NOT NULL,
	pm_startche char(10) NOT NULL,
	pm_startla int NOT NULL,
	if_pm_start int NOT NULL,
	pm_endchs char(10) NOT NULL,
	pm_end char(10) NOT NULL,
	pm_endche char(10) NOT NULL,
	pm_endla int NOT NULL,
	if_pm_end int NOT NULL,
	monday char(10) NOT NULL,
	tuesday int NOT NULL,
	wednesday int NOT NULL,
	thirsday int NOT NULL,
	friday int NOT NULL,
	saturday int NOT NULL,
	sunday int NOT NULL
)

CREATE TABLE checkwork_record(
	id int IDENTITY(1,1) NOT NULL,
	am_start char(10) NULL,
	am_end char(10) NULL,
	pm_start char(10) NULL,
	pm_end char(10) NULL,
	latetimes int NOT NULL,
	earlytimes int NOT NULL,
	uncheck int NOT NULL,
	leavetimes int NOT NULL,
	if_finish int NOT NULL,
	newdate char(20) NOT NULL,
	username char(30) NOT NULL,
	department char(30) NOT NULL
)

CREATE TABLE checkwork_scope(
	id int IDENTITY(1,1) NOT NULL,
	department char(40) NOT NULL,
	role char(40) NOT NULL,
	newdate char(20) NOT NULL
)

CREATE TABLE checkwork_leave(
	id int IDENTITY(1,1) NOT NULL,
	leavetime char(10) NOT NULL,
	cometime char(10) NOT NULL,
	content nchar(800) NOT NULL,
	state char(30) NOT NULL,
	sp_yj nvarchar(300) NULL,
	sp_man char(30) NULL,
	newdate char(10) NOT NULL,
	username char(30) NOT NULL
)

CREATE TABLE tntxiaoa_checkwork_record(
	id int IDENTITY(1,1) NOT NULL,
	check_time datetime,
	user_name varchar(30) NOT NULL
)

CREATE TABLE tntxiaoa_client_subscribe(
	id int IDENTITY(1,1) NOT NULL,
	subscribe_time datetime,
	create_time datetime,
	user_name varchar(30) NOT NULL,
	client_id int
)

CREATE TABLE progjh(
	id int IDENTITY(1,1) NOT NULL,
	xmid nvarchar(20) NULL,
	jhnumber nvarchar(30) NULL,
	jhname nvarchar(80) NULL,
	startdt nvarchar(50) NULL,
	enddt nvarchar(50) NULL,
	menber nvarchar(50) NULL,
	content ntext NULL,
	remark nvarchar(300) NULL
)

CREATE TABLE proggz(
	id int IDENTITY(1,1) NOT NULL,
	xmid nvarchar(20) NULL,
	hbnumber nvarchar(20) NULL,
	startdt nvarchar(50) NULL,
	topic nvarchar(60) NULL,
	menber nvarchar(30) NULL,
	content ntext NULL,
	remark nvarchar(300) NULL,
	spman nvarchar(10) NULL,
	spdate nvarchar(10) NULL,
	spyj nvarchar(500) NULL
)

CREATE TABLE ddtransportation(
	id int IDENTITY(1,1) NOT NULL,
	ddid varchar(50) NOT NULL,
	coname varchar(150) NOT NULL,
	invoice nvarchar(20) NOT NULL,
	transportation varchar(150) NOT NULL,
	aimport varchar(80) NULL,
	startport varchar(80) NULL,
	package varchar(150) NULL,
	linkman varchar(60) NULL,
	linktel nvarchar(50) NULL,
	sendcompany nvarchar(80) NULL,
	slinkman nvarchar(50) NULL,
	slinktel nvarchar(50) NULL,
	remark ntext NULL,
	co_number char(30) NULL
)

CREATE TABLE activity_type(
	id int IDENTITY(1,1) NOT NULL,
	act_name nvarchar(100) NULL
)

CREATE TABLE p_pic(
	id int IDENTITY(1,1) NOT NULL,
	oid char(10) NULL,
	pic_sm nvarchar(100) NULL,
	pic_path nvarchar(50) NULL
)

create table export_task(
	id varchar(50) NOT NULL,
	name varchar(100),
	username varchar(50) NOT NULL,
	status int,
	create_time datetime,
	finish_time datetime,
	remark text
	
	
)

CREATE TABLE jcsp(
	id int IDENTITY(1,1) NOT NULL,
	dept char(30) NULL,
	role char(15) NULL,
	dd_man char(15) NOT NULL,
	fif char(10) NOT NULL,
	fspman varchar(50) NOT NULL,
	firspif char(10) NULL,
	firspman char(20) NULL,
	remark varchar(350) NULL,
	dd_date datetime NOT NULL
)

CREATE TABLE lawtable(
	id int IDENTITY(1,1) NOT NULL,
	titel nvarchar(150) NULL,
	km_types nvarchar(90) NULL,
	content ntext NULL,
	km_fa ntext NULL,
	username nvarchar(50) NULL,
	fvdate nvarchar(50) NULL,
	dept char(70) NULL,
	deptjb char(10) NULL
)

CREATE TABLE f_pic(
	id int IDENTITY(1,1) NOT NULL,
	oid char(10) NULL,
	pic_sm nvarchar(100) NULL,
	pic_path nvarchar(50) NULL
)

create table knowledge_attachment(
	id int IDENTITY(1,1) NOT NULL,
	knowledge_id int not NULL,
	name nvarchar(100) NULL,
	file_path nvarchar(500) NULL,
	create_time datetime
)	

CREATE TABLE cust_sale_total(
	id int IDENTITY(1,1) NOT NULL,
	man char(15) NULL,
	coname nvarchar(200) NULL,
	sub_num int NULL,
	pro_number nvarchar(50) NULL,
	pro_num int NULL,
	pro_sale_money nvarchar(150) NULL,
	pro_cg_money nvarchar(150) NULL,
	pro_lr_money nvarchar(150) NULL,
	pro_lr_rate nvarchar(150) NULL
)

CREATE TABLE name_sale_total(
	id int IDENTITY(1,1) NOT NULL,
	man char(15) NULL,
	coname nvarchar(100) NULL,
	sub_num int NULL,
	pro_number decimal(18, 2) NULL,
	pro_num int NULL,
	pro_sale_money decimal(18, 2) NULL,
	pro_sk_money decimal(18, 0) NULL,
	pro_cg_money decimal(18, 2) NULL,
	pro_other_money decimal(18, 2) NULL,
	pro_lr_money decimal(18, 2) NULL,
	pro_lr_rate decimal(18, 2) NULL
)

CREATE TABLE xjpro(
	id int IDENTITY(1,1) NOT NULL,
	ddid varchar(10) NOT NULL,
	epro varchar(300) NOT NULL,
	cpro nvarchar(100) NULL,
	cpro2 nvarchar(100) NULL,
	num int NOT NULL,
	unit varchar(50) NULL,
	selljg decimal(18, 6) NULL,
	money varchar(50) NULL,
	cgpro_ydatetime nvarchar(50) NULL,
	cgpro_num int NOT NULL,
	cgpro_sdatetime nvarchar(15) NULL,
	remark nvarchar(300) NULL,
	supplier nvarchar(50) NULL,
	rate int NULL,
	wid char(10) NULL,
	pro_sup_no nvarchar(300) NULL
)

create table design(
	id int IDENTITY(1,1) NOT NULL,
	logo varchar(100),
	banner_html text
)

CREATE TABLE gz_pic(
	id int IDENTITY(1,1) NOT NULL,
	oid char(10) NULL,
	pic_sm nvarchar(100) NULL,
	pic_path nvarchar(50) NULL
)

CREATE TABLE trade_policy(
	id int IDENTITY(1,1) NOT NULL,
	number char(10) NULL,
	rg_datetime datetime NULL,
	man char(10) NULL,
	dept char(20) NULL,
	deptjb char(10) NULL,
	trade_subject nvarchar(140) NULL,
	trade_name nvarchar(100) NULL,
	trade_content ntext NULL,
	bring_date datetime NULL,
	dis_date datetime NULL,
	trade_extent nvarchar(300) NULL,
	trade_source nvarchar(100) NULL,
	spman char(10) NULL,
	states char(10) NULL,
	spyj nvarchar(200) NULL,
	in_no int NULL
)

CREATE TABLE c_pic(
	id int IDENTITY(1,1) NOT NULL,
	oid char(10) NULL,
	pic_sm nvarchar(100) NULL,
	pic_path nvarchar(50) NULL
)

create table menu {
	id int IDENTITY(1,1) NOT NULL,
	name varchar(100) NOT NULL,
	url varchar(200),
	order_no int,
	pid int
}


